/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ProtoService_CONSTANTS_H
#define ProtoService_CONSTANTS_H

#include "ProtoService_types.h"

namespace proto_rpc {

class ProtoServiceConstants {
 public:
  ProtoServiceConstants();

};

extern const ProtoServiceConstants g_ProtoService_constants;

} // namespace

#endif
