// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "ProtoRpcService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using namespace  ::proto_rpc;

class ProtoRpcServiceHandler : virtual public ProtoRpcServiceIf {
 public:
  ProtoRpcServiceHandler() {
    // Your initialization goes here
  }

  void dealTwowayMessage(ProtoReply& _return, const ProtoRequest& rq) {
    // Your implementation goes here
    printf("dealTwowayMessage\n");
  }

  void dealOnewayMessage(const ProtoRequest& rq) {
    // Your implementation goes here
    printf("dealOnewayMessage\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  ::apache::thrift::stdcxx::shared_ptr<ProtoRpcServiceHandler> handler(new ProtoRpcServiceHandler());
  ::apache::thrift::stdcxx::shared_ptr<TProcessor> processor(new ProtoRpcServiceProcessor(handler));
  ::apache::thrift::stdcxx::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::apache::thrift::stdcxx::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::apache::thrift::stdcxx::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

