/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ProtoService_constants.h"

namespace proto_rpc {

const ProtoServiceConstants g_ProtoService_constants;

ProtoServiceConstants::ProtoServiceConstants() {
}

} // namespace

