//
//  RpcTypes.h
//  rpcserver_unittest
//
//  Created by 周 斌 on 15/1/6.
//  Copyright (c) 2015年 周 斌. All rights reserved.
//

#ifndef rpcserver_unittest_RpcTypes_h
#define rpcserver_unittest_RpcTypes_h

#include <limits.h>

enum
{
    DEF_DEFAULT_RPC_PACKET_BASE = 100000,
    DEF_USER_PRIVILEGE_BASE = int(DEF_DEFAULT_RPC_PACKET_BASE + 200),

    DEF_USER_MIGRATION_BASE = int(DEF_DEFAULT_RPC_PACKET_BASE + 1000),

    DEF_USER_GOODS_BASE = int(DEF_DEFAULT_RPC_PACKET_BASE + 1100),

    DEF_USER_DRESS_BASE = int(DEF_DEFAULT_RPC_PACKET_BASE + 1200),

    DEF_USER_COMPONENT_BASE = int(DEF_DEFAULT_RPC_PACKET_BASE + 1300),

    DEF_USER_SCENERY_BASE = int(DEF_DEFAULT_RPC_PACKET_BASE + 1400),
    DEF_GAME_ACCOUNT_BASE = int(DEF_DEFAULT_RPC_PACKET_BASE + 1500),

    DEF_USER_BUBBLE_BASE = int(DEF_DEFAULT_RPC_PACKET_BASE + 1600),

    DEF_REGISTER_BASE = int(DEF_DEFAULT_RPC_PACKET_BASE + 1700),

    DEF_GAME_VALET_BASE = int(DEF_DEFAULT_RPC_PACKET_BASE + 1800),

    DEF_MONEY_BASE = int(DEF_DEFAULT_RPC_PACKET_BASE + 1900),

    DEF_USER_INFLUENCE_BASE = int(DEF_DEFAULT_RPC_PACKET_BASE + 2000),

    DEF_USER_FRIEND_BASE = int(DEF_DEFAULT_RPC_PACKET_BASE + 2100),

    DEF_GAME_VALET_PROPERTY = int(DEF_DEFAULT_RPC_PACKET_BASE + 2200),

    DEF_USER_DEGREE_FRIEND_BASE = int(DEF_DEFAULT_RPC_PACKET_BASE + 2300),

    DEF_RPC_FRIENDSRANK_BASE = int(DEF_DEFAULT_RPC_PACKET_BASE + 2400),

    DEF_RPC_NPC_BASE = int(DEF_DEFAULT_RPC_PACKET_BASE + 2500),

    DEF_RPC_VALET_SKILL_BASE = int(DEF_DEFAULT_RPC_PACKET_BASE + 2600),

    DEF_RPC_PPMESSQUE_BASE = int(DEF_DEFAULT_RPC_PACKET_BASE + 2700),

    DEF_RPC_BAG_ITEM_BASE = int(DEF_DEFAULT_RPC_PACKET_BASE + 2800),

    DEF_SYS_RED_PACKET_BASE = int(DEF_DEFAULT_RPC_PACKET_BASE + 2900),

    DEF_USER_PACKAGE_BASE = int(DEF_DEFAULT_RPC_PACKET_BASE + 3000),

    DEF_RPC_NPC_LIBRARY_BASE = int(DEF_DEFAULT_RPC_PACKET_BASE + 3100),

    DEF_RPC_PRISON__BASE = int(DEF_DEFAULT_RPC_PACKET_BASE + 3200),

    DEF_RPC_SNATCH_BASE = int(DEF_DEFAULT_RPC_PACKET_BASE + 3300),

    DEF_RPC_SYS_AWARD_BASE = int(DEF_DEFAULT_RPC_PACKET_BASE + 3400),

    DEF_RPC_NPC_LUCKY_CARD_BASE = int(DEF_DEFAULT_RPC_PACKET_BASE + 3500),

    DEF_RPC_NPC_VALET_SLOT_INFO_BASE = int(DEF_DEFAULT_RPC_PACKET_BASE + 3600),

    DEF_RPC_VALET_SLOT_AWARD_BASE = int(DEF_DEFAULT_RPC_PACKET_BASE + 3700),

    DEF_RPC_VALET_HATE_BASE = int(DEF_DEFAULT_RPC_PACKET_BASE + 3800),

    DEF_RPC_WEB_RPC_BASE = int(DEF_DEFAULT_RPC_PACKET_BASE + 3900),//处理c服务和php服务交互接口

    DEF_RPC_EQUIP_DBCS_RPC_BASE = int(DEF_DEFAULT_RPC_PACKET_BASE + 4000),//装备实例存储服务

    DEF_RPC_GOODS_DROP_MAX_LIMIT_RPC_BASE = int(DEF_DEFAULT_RPC_PACKET_BASE + 4050),//每天物品掉落上限查询服务

    DEF_RPC_USER_ID_VERIFY_RPC_BASE = int(DEF_DEFAULT_RPC_PACKET_BASE + 4100),//查询合法用户id范围

    DEF_RPC_USER_NEW_CARD_RPC_BASE  = int(DEF_DEFAULT_RPC_PACKET_BASE + 4200),// 新类型车

    DEF_REDPACK_GAME_BASE = int(DEF_DEFAULT_RPC_PACKET_BASE + 4300), // 抢红包游戏

    DEF_RPC_IMPRISON_OPERATE_BASE	= int(DEF_DEFAULT_RPC_PACKET_BASE + 4400),  //囚禁操作RPC接口

    DEF_CONTROL_BASE = int(DEF_DEFAULT_RPC_PACKET_BASE + 5000),

    DEF_CHATBAR_BASE = int(DEF_DEFAULT_RPC_PACKET_BASE + 6000),

    DEF_COMBAT_BASE = int(DEF_DEFAULT_RPC_PACKET_BASE + 6500),

    DEF_RPC_USER_VIP_LEVEL_BASE = int(DEF_DEFAULT_RPC_PACKET_BASE + 6600),

    DEF_RPC_HOUSE_KEEPER_BASE = int(DEF_DEFAULT_RPC_PACKET_BASE + 6700),

    DEF_RPC_FAMILY_BASE = int(DEF_DEFAULT_RPC_PACKET_BASE + 6800),

    DEF_RPC_QUERY_USER_ONLINE_BASE = int(DEF_DEFAULT_RPC_PACKET_BASE + 6900),

    DEF_RPC_LEVEL_CONSUME_BASE = int(DEF_DEFAULT_RPC_PACKET_BASE + 7100), // 潜能

    DEF_RPC_SYSTEM_RECOMMEND_BASE = int(DEF_DEFAULT_RPC_PACKET_BASE + 7200),//系统推荐

    DEF_RPC_CAR_MANAGER_BASE = int(DEF_DEFAULT_RPC_PACKET_BASE + 7300), // 车辆

    DEF_RPC_CHEST_RECOMMEND_BASE = int(DEF_DEFAULT_RPC_PACKET_BASE + 7400), // 宝箱推荐

    DEF_RPC_PHP_SERVER_BASE    = int(DEF_DEFAULT_RPC_PACKET_BASE + 7500),   // PHP 与 H5等调用的服务段

    DEF_BUFF_ADDITION_BASE = int(DEF_DEFAULT_RPC_PACKET_BASE + 7600),//buff

    DEF_RPC_GOLDCOIN_BASE  = int(DEF_DEFAULT_RPC_PACKET_BASE + 7800), // goldcoin

    DEF_VALET_USER_DATA_BASE = int(DEF_DEFAULT_RPC_PACKET_BASE + 7900),//跟班数据

    DEF_RPC_FANS_DATA_BASE = int(DEF_DEFAULT_RPC_PACKET_BASE + 8000), //粉丝团

	DEF_RPC_CAPSULE_BASE = int(DEF_DEFAULT_RPC_PACKET_BASE + 8100), //胶囊
	
	DEF_RPC_WORK_SHOP_BASE = int(DEF_DEFAULT_RPC_PACKET_BASE + 8200), // 工坊

    DEF_RPC_LOGIN_PACKET_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 99998),   //rpc 登录专用包，这个包将标明客户端的连接身份和地址用于解决rpc接口无法识别对端身份的问题
    DEF_RPC_LOGIN_PACKET_RS = int(DEF_DEFAULT_RPC_PACKET_BASE + 99999),   // plate内部会直接把这个包处理掉，应用层无感知。

    DEF_RPC_MANAGEMENT_BASE = int(DEF_DEFAULT_RPC_PACKET_BASE + 10000),

    DEF_USER_COORDINATE_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE),

    DEF_USER_COORDINATE_RS = int(DEF_DEFAULT_RPC_PACKET_BASE + 1),

    DEF_USER_NEW_STATE_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 2),

    DEF_USER_NEW_STATE_RS = int(DEF_DEFAULT_RPC_PACKET_BASE + 3),

    DEF_GIVE_USER_GIFTPACK_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 4),

    DEF_GIVE_USER_GIFTPACK_RS = int(DEF_DEFAULT_RPC_PACKET_BASE + 5),

    DEF_USER_OPEN_GIFTPACK_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 6),

    DEF_USER_OPEN_GIFTPACK_RS = int(DEF_DEFAULT_RPC_PACKET_BASE + 7),

    DEF_USER_PRIVILEGE_INFO_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 8),

    DEF_USER_PRIVILEGE_INFO_RS = int(DEF_DEFAULT_RPC_PACKET_BASE + 9),

    DEF_USER_STAY_CHATROOM_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 10),

    DEF_USER_STAY_CHATROOM_RS = int(DEF_DEFAULT_RPC_PACKET_BASE + 11),

    DEF_USER_FULL_PRIVILEGE_INFO_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 12),

    DEF_USER_FULL_PRIVILEGE_INFO_RS = int(DEF_DEFAULT_RPC_PACKET_BASE + 13),

    DEF_CLEAR_USER_PRIVILEGE_INFO_ID = int(DEF_DEFAULT_RPC_PACKET_BASE + 14),

    DEF_SET_USER_PRIVILEGE_INFO_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 15),

    DEF_GENERAL_RPC_REPLY = int(DEF_DEFAULT_RPC_PACKET_BASE + 15),

    DEF_USER_DISPLAY_INFO_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 16),

    DEF_USER_DISPLAY_INFO_RS = int(DEF_DEFAULT_RPC_PACKET_BASE + 17),

    DEF_GET_BOSS_GIFT_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 18),

    DEF_GET_BOSS_GIFT_RS = int(DEF_DEFAULT_RPC_PACKET_BASE + 19),

    DEF_USER_WEALTH_CHANGE_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 20),

    DEF_USER_WEALTH_INFO_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 21),

    DEF_USER_WEALTH_INFO_RS = int(DEF_DEFAULT_RPC_PACKET_BASE + 22),

    DEF_GET_USER_LEVEL_INFO_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 23),
    DEF_GET_USER_LEVEL_INFO_RS = int(DEF_DEFAULT_RPC_PACKET_BASE + 24),

    DEF_GET_USER_TUTOR_FINISHED_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 25),
    DEF_GET_USER_TUTOR_FINISHED_RS = int(DEF_DEFAULT_RPC_PACKET_BASE + 26),

    DEF_GET_USER_ITEMS_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 27),
    DEF_GET_USER_ITEMS_RS = int(DEF_DEFAULT_RPC_PACKET_BASE + 28),

    DEF_COST_USER_SKILL_ITEMS_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 29),
    DEF_COST_USER_SKILL_ITEMS_RS = int(DEF_DEFAULT_RPC_PACKET_BASE + 30),

    DEF_CHANGE_USER_ITEM_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 31),
    DEF_CHANGE_USER_ITEM_RS = int(DEF_DEFAULT_RPC_PACKET_BASE + 32),

    DEF_SET_USER_TUTOR_FINISHED_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 33),
    DEF_SET_USER_TUTOR_FINISHED_RS = int(DEF_DEFAULT_RPC_PACKET_BASE + 34),

    DEF_SET_USER_LEVEL_INFO_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 35),
    DEF_SET_USER_LEVEL_INFO_RS = int(DEF_DEFAULT_RPC_PACKET_BASE + 36),

    DEF_USER_INFO_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 37),
    DEF_USER_INFO_RS = int(DEF_DEFAULT_RPC_PACKET_BASE + 38),

    DEF_CLEAR_USER_DISPLAY_INFO_ID = int(DEF_DEFAULT_RPC_PACKET_BASE + 39),

    DEF_USER_GAIN_GIFT_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 40),
    DEF_USER_GAIN_GIFT_RS = int(DEF_DEFAULT_RPC_PACKET_BASE + 41),

    DEF_USER_INFO_LIGHT_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 42),
    DEF_USER_INFO_LIGHT_RS = int(DEF_DEFAULT_RPC_PACKET_BASE + 43),

    DEF_ADD_USER_MONEY_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 44),
    DEF_ADD_USER_MONEY_RS = int(DEF_DEFAULT_RPC_PACKET_BASE + 45),

    DEF_ADD_USER_WEALTH_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 46),
    DEF_ADD_USER_WEALTH_RS = int(DEF_DEFAULT_RPC_PACKET_BASE + 47),

    DEF_CHARGE_USER_MONEY_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 48),//UdbcsRpcDef::ChargeMoneyRQ钻石充值接口ID
    DEF_CHARGE_USER_MONEY_RS = int(DEF_DEFAULT_RPC_PACKET_BASE + 49),

    DEF_CONSUME_USER_MONEY_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 50),//UdbcsRpcDef::ConsumeUserMoneyRQ 消费钻石扣费接口ID
    DEF_CONSUME_USER_MONEY_RS = int(DEF_DEFAULT_RPC_PACKET_BASE + 51),

    DEF_GET_USER_MONEY_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 52),   //BossRpcDef::UserWealthInfoRq暂时只用于请求钻石余额接口ID
    DEF_GET_USER_MONEY_RS = int(DEF_DEFAULT_RPC_PACKET_BASE + 53),   //

    DEF_USER_CHANNEL_CHARM_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 54),
    DEF_USER_CHANNEL_CHARM_RS = int(DEF_DEFAULT_RPC_PACKET_BASE + 55),

    DEF_USER_CHANNEL_CHARM_RQ_OLD = int(DEF_DEFAULT_RPC_PACKET_BASE + 56),
    DEF_USER_CHANNEL_CHARM_RS_OLD = int(DEF_DEFAULT_RPC_PACKET_BASE + 57),

    DEF_USER_CHANNEL_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 58),
    DEF_USER_CHANNEL_RS = int(DEF_DEFAULT_RPC_PACKET_BASE + 59),


    DEF_USER_MONEYIN_LOG_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 56),
    DEF_USER_MONEYOUT_LOG_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 57),
    DEF_USER_MONEY_LOG_RS = int(DEF_DEFAULT_RPC_PACKET_BASE + 58),

    DEF_SVR_GET_USER_ACHIVE_INFO_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 65),  //1 读取用户成就的详细信息
    DEF_SVR_GET_USER_ACHIVE_INFO_RS = int(DEF_DEFAULT_RPC_PACKET_BASE + 66),

    DEF_SVR_GET_USER_COMPLETE_ACHIVE_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 67),   //2 读取用户已完成的成就
    DEF_SVR_GET_USER_COMPLETE_ACHIVE_RS = int(DEF_DEFAULT_RPC_PACKET_BASE + 68),

    DEF_SVR_GET_USER_ACHIVE_AWARD_STATUS_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 69),  //3 读取用户成就对应等级奖励是否获取
    DEF_SVR_GET_USER_ACHIVE_AWARD_STATUS_RS = int(DEF_DEFAULT_RPC_PACKET_BASE + 70),

    DEF_SVR_ADD_GIFT_ACHIVE_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 71), //4 累积礼物成就数据
    DEF_SVR_ADD_GIFT_ACHIVE_RS = int(DEF_DEFAULT_RPC_PACKET_BASE + 72),

    DEF_SVR_ADD_LUCKY_ACHIVE_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 73), //5 累积幸运成就数据
    DEF_SVR_ADD_LUCKY_ACHIVE_RS = int(DEF_DEFAULT_RPC_PACKET_BASE + 74),

    DEF_SVR_ADD_ACTIVITY_ACHIVE_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 75), //6 累积活动成就数据
    DEF_SVR_ADD_ACTIVITY_ACHIVE_RS = int(DEF_DEFAULT_RPC_PACKET_BASE + 76),

    DEF_SVR_ADD_RANK_ACHIVE_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 77),   //7 累积榜单成就数据
    DEF_SVR_ADD_RANK_ACHIVE_RS = int(DEF_DEFAULT_RPC_PACKET_BASE + 78),

    DEF_SVR_ADD_USER_NEW_ACHIVE_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 79),//8 用户添加新成就
    DEF_SVR_ADD_USER_NEW_ACHIVE_RS = int(DEF_DEFAULT_RPC_PACKET_BASE + 80),

    DEF_SVR_SET_ACHIVE_AWARD_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 81),   //9 设置用户成就对应等级奖励已领取
    DEF_SVR_SET_ACHIVE_AWARD_RS = int(DEF_DEFAULT_RPC_PACKET_BASE + 82),

    DEF_SVR_GET_USER_AVHIVE_CURLEVEL_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 83),  //10 读取用户当前等级
    DEF_SVR_GET_USER_AVHIVE_CURLEVEL_RS = int(DEF_DEFAULT_RPC_PACKET_BASE + 84),

    DEF_SVR_GET_USER_GIFT_ACHIVE_INFO_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 85),  //11 用户礼物成就使用单独接口ID但接口不变
    DEF_SVR_GET_USER_GIFT_ACHIVE_INFO_RS = int(DEF_DEFAULT_RPC_PACKET_BASE + 86),

    DEF_SERVER_GET_ADDITION_VALUE_ARRAY_BY_GROUP_ID_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 96),
    DEF_SERVER_GET_ADDITION_VALUE_ARRAY_BY_GROUP_ID_RS = int(DEF_DEFAULT_RPC_PACKET_BASE + 97),

    DEF_SVR_ACHIVE_CHANGE_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 98),
    DEF_SVR_ACHIVE_CHANGE_RS = int(DEF_DEFAULT_RPC_PACKET_BASE + 99),

    DEF_USER_ADD_TITLE_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 100),
    DEF_USER_REMOVE_TITLE_ID = int(DEF_DEFAULT_RPC_PACKET_BASE + 101),

    DEF_USER_AVALIBLE_TITLE_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 102),
    DEF_USER_AVALIBLE_TITLE_RS = int(DEF_DEFAULT_RPC_PACKET_BASE + 103),

    DEF_USER_CHOSE_TITLE_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 104),

    DEF_USER_DISPLAY_TITLE_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 105),
    DEF_USER_DISPLAY_TITLE_RS = int(DEF_DEFAULT_RPC_PACKET_BASE + 106),

    DEF_ADD_USER_SKILL_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 107),
    DEF_ADD_USER_SKILL_RS = int(DEF_DEFAULT_RPC_PACKET_BASE + 108),

    DEF_UPGRADE_USER_SKILL_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 109),
    DEF_UPGRADE_USER_SKILL_RS = int(DEF_DEFAULT_RPC_PACKET_BASE + 110),

    DEF_GET_USER_SKILL_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 111),
    DEF_GET_USER_SKILL_RS = int(DEF_DEFAULT_RPC_PACKET_BASE + 112),

    DEF_ADDUP_NUMBER_UPDATE_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 113),
    DEF_ADDUP_NUMBER_UPDATE_RS = int(DEF_DEFAULT_RPC_PACKET_BASE + 114),

    //抢车位相关
    //停车
    DEF_SVR_CARPARK_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 115),
    DEF_SVR_CARPARK_RS = int(DEF_DEFAULT_RPC_PACKET_BASE + 116),
    //取车
    DEF_SVR_TAKECAR_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 117),
    DEF_SVR_TAKECAR_RS = int(DEF_DEFAULT_RPC_PACKET_BASE + 118),
    //贴条
    DEF_SVR_JOINTSTRIP_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 119),
    DEF_SVR_JOINTSTRIP_RS = int(DEF_DEFAULT_RPC_PACKET_BASE + 120),
    //信息初始化
    DEF_SVE_USER_CARPARK_INIT_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 121),
    DEF_SVE_USER_CARPARK_INIT_RS = int(DEF_DEFAULT_RPC_PACKET_BASE + 122),
    //用户信息查询
    DEF_SVR_USER_INFO_CARPARK_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 123),
    DEF_SVR_USER_INFO_CARPARK_RS = int(DEF_DEFAULT_RPC_PACKET_BASE + 124),
    //多用户信息查询
    DEF_SVR_USER_INFO_CARPARK_MULTI_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 125),
    DEF_SVR_USER_INFO_CARPARK_MULTI_RS = int(DEF_DEFAULT_RPC_PACKET_BASE + 126),

    //停车历史查询
    DEF_SVR_USER_CARPARK_HISTORY_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 127),
    DEF_SVR_USER_CARPARK_HISTORY_RS = int(DEF_DEFAULT_RPC_PACKET_BASE + 128),
    //抢车位推荐
    DEF_SVR_USER_CARPARK_RECOMMEND_RQ  = int(DEF_DEFAULT_RPC_PACKET_BASE + 129),
    DEF_SVR_USER_CARPARK_RECOMMEND_RS  = int(DEF_DEFAULT_RPC_PACKET_BASE + 130),
    //小跟班推荐
    DEF_SVR_USER_TEAMMATE_RECOMMEND_RQ  = int(DEF_DEFAULT_RPC_PACKET_BASE + 131),
    DEF_SVR_USER_TEAMMATE_RECOMMEND_RS  = int(DEF_DEFAULT_RPC_PACKET_BASE + 132),

    //抢车位广场推荐
    DEF_SVR_USER_CARPARK_RECOMMEND_FOURM_RQ  = int(DEF_DEFAULT_RPC_PACKET_BASE + 133),
    DEF_SVR_USER_CARPARK_RECOMMEND_FOURM_RS  = int(DEF_DEFAULT_RPC_PACKET_BASE + 134),
    //小跟班广场推荐
    DEF_SVR_USER_TEAMMATE_RECOMMEND_FOURM_RQ  = int(DEF_DEFAULT_RPC_PACKET_BASE + 135),
    DEF_SVR_USER_TEAMMATE_RECOMMEND_FOURM_RS  = int(DEF_DEFAULT_RPC_PACKET_BASE + 136),
    //聊天广场推荐
    DEF_SVR_USER_CHAT_RECOMMEND_FOURM_RQ  = int(DEF_DEFAULT_RPC_PACKET_BASE + 137),
    DEF_SVR_USER_CHAT_RECOMMEND_FOURM_RS  = int(DEF_DEFAULT_RPC_PACKET_BASE + 138),

    //所有服上的所有技能
    DEF_GET_USER_ALL_SECTION_SKILL_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 139),
    DEF_GET_USER_ALL_SECTION_SKILL_RS = int(DEF_DEFAULT_RPC_PACKET_BASE + 140),

    //举报
    DEF_SVR_USER_CARPARK_REPORT_RQ  = int(DEF_DEFAULT_RPC_PACKET_BASE + 141),
    DEF_SVR_USER_CARPARK_REPORT_RS  = int(DEF_DEFAULT_RPC_PACKET_BASE + 142),
    //举报获得收益
    DEF_SVR_USER_CARPARK_REPORT_INCOME_RQ  = int(DEF_DEFAULT_RPC_PACKET_BASE + 143),
    DEF_SVR_USER_CARPARK_REPORT_INCOME_RS  = int(DEF_DEFAULT_RPC_PACKET_BASE + 144),

    //新用户信息查询
    DEF_SVR_NEW_USER_INFO_QUERY_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 145),
    DEF_SVR_NEW_USER_INFO_QUERY_RS = int(DEF_DEFAULT_RPC_PACKET_BASE + 146),

    //扣指定用户钻石packid
    DEF_SVR_CONSUME_USER_DIAMOND_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 147),
    DEF_SVR_CONSUME_USER_DIAMOND_RS = int(DEF_DEFAULT_RPC_PACKET_BASE + 148),

    //比拼推荐
    DEF_SVR_USER_TEAMMATE_RECOMMEND_FIGHT_RQ  = int(DEF_DEFAULT_RPC_PACKET_BASE + 149),
    DEF_SVR_USER_TEAMMATE_RECOMMEND_FIGHT_RS  = int(DEF_DEFAULT_RPC_PACKET_BASE + 150),

    // 跟班历史事件查询
    DEF_USER_VALET_BROADCAST_LIST_RQ        = int(DEF_DEFAULT_RPC_PACKET_BASE + 153),
    DEF_USER_VALET_BROADCAST_LIST_RS        = int(DEF_DEFAULT_RPC_PACKET_BASE + 154),

    // 用户幸运值查询
    DEF_USER_LUCKY_QUERY_RQ     = int(DEF_DEFAULT_RPC_PACKET_BASE + 155),
    DEF_USER_LUCKY_QUERY_RS     = int(DEF_DEFAULT_RPC_PACKET_BASE + 156),
    // 删除用户信息
    DEF_USER_INFO_DELETE_RQ     = int(DEF_DEFAULT_RPC_PACKET_BASE + 157),
    DEF_USER_INFO_DELETE_RS     = int(DEF_DEFAULT_RPC_PACKET_BASE + 158),

    // 修改用户信息
    DEF_USER_INFO_UPDATE_RQ     = int(DEF_DEFAULT_RPC_PACKET_BASE + 159),
    DEF_USER_INFO_UPDATE_RS     = int(DEF_DEFAULT_RPC_PACKET_BASE + 160),

    // 查询产出npc碎片概率
    DEF_NPC_FRAGMENT_LUCKY_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 161),
    DEF_NPC_FRAGMENT_LUCKY_RS = int(DEF_DEFAULT_RPC_PACKET_BASE + 162),

    // 查询用户信息（中度）
    DEF_USER_INFO_MID_RQ    = int(DEF_DEFAULT_RPC_PACKET_BASE + 163),
    DEF_USER_INFO_MID_RS    = int(DEF_DEFAULT_RPC_PACKET_BASE + 164),

    // 查询paipaixiu token接口
    DEF_GET_USER_XIU_TOKEN_INFO_RQ  = int(DEF_DEFAULT_RPC_PACKET_BASE + 165),
    DEF_GET_USER_XIU_TOKEN_INFO_RS  = int(DEF_DEFAULT_RPC_PACKET_BASE + 166),

    //更新接口
    DEF_UPDATE_USER_XIU_TOKEN_INFO_RQ   = int(DEF_DEFAULT_RPC_PACKET_BASE + 167),
    DEF_UPDATE_USER_XIU_TOKEN_INFO_RS   = int(DEF_DEFAULT_RPC_PACKET_BASE + 168),

    // 更新派派秀背景id
    DEF_UPDATE_USER_XIU_BG_ID_RQ        = int(DEF_DEFAULT_RPC_PACKET_BASE + 169),
    DEF_UPDATE_USER_XIU_BG_ID_RS        = int(DEF_DEFAULT_RPC_PACKET_BASE + 170),

    // 学习图纸上的技能请求
    DEF_LEARN_SHOW_DRAW_INFO_RQ  = int(DEF_DEFAULT_RPC_PACKET_BASE + 171),
    DEF_LEARN_SHOW_DRAW_INFO_RS  = int(DEF_DEFAULT_RPC_PACKET_BASE + 172),

    // 获取所有已学习的图纸列表
    DEF_GET_LEARNED_SHOW_DRAW_INFOS_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 173),
    DEF_GET_LEARNED_SHOW_DRAW_INFOS_RS = int(DEF_DEFAULT_RPC_PACKET_BASE + 174),

    // 获取所有未学习的图纸列表
    DEF_GET_UNLEARNED_SHOW_DRAW_INFOS_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 175),
    DEF_GET_UNLEARNED_SHOW_DRAW_INFOS_RS = int(DEF_DEFAULT_RPC_PACKET_BASE + 176),
	
	// 数据加密
	DEF_DATA_ENCRYPT_RQ       = int(DEF_DEFAULT_RPC_PACKET_BASE + 177),
	DEF_DATA_ENCRYPT_RS       = int(DEF_DEFAULT_RPC_PACKET_BASE + 178),
	// 数据解密
	DEF_DATA_DECRYPT_RQ       = int(DEF_DEFAULT_RPC_PACKET_BASE + 179),
	DEF_DATA_DECRYPT_RS       = int(DEF_DEFAULT_RPC_PACKET_BASE + 180),
	
	DEF_ITEM_CAP_RQ   =  int(DEF_DEFAULT_RPC_PACKET_BASE + 181),
	DEF_ITEM_CAP_RS   =  int(DEF_DEFAULT_RPC_PACKET_BASE + 182),
    
    //只使用普通钻石packid
    DEF_CONSUME_USER_NORMAL_DIAMOND_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 183),
    DEF_CONSUME_USER_NORMAL_DIAMOND_RS = int(DEF_DEFAULT_RPC_PACKET_BASE + 184),
	
	//unixsocket_risk_level_rpc,监控、校验黑名单报警服务
	DEF_GET_USER_RISK_LEVEL_RQ = int(DEF_DEFAULT_RPC_PACKET_BASE + 185),
    DEF_GET_USER_RISK_LEVEL_RS = int(DEF_DEFAULT_RPC_PACKET_BASE + 186),

    // 跟班槽位查询
    DEF_USER_VALET_SLOT_INFO_RQ     = int(DEF_RPC_NPC_VALET_SLOT_INFO_BASE + 1),
    DEF_USER_VALET_SLOT_INFO_RS     = int(DEF_RPC_NPC_VALET_SLOT_INFO_BASE + 2),

    // 跟班单个槽位是否可用查询
    DEF_USER_VALET_SLOT_QUERY_RQ    = int(DEF_RPC_NPC_VALET_SLOT_INFO_BASE + 3),
    DEF_USER_VALET_SLOT_QUERY_RS    = int(DEF_RPC_NPC_VALET_SLOT_INFO_BASE + 4),

    // 挑选一个可用的槽位
    DEF_VALET_PICK_ONE_VALID_SLOT_RQ = int(DEF_RPC_NPC_VALET_SLOT_INFO_BASE + 5),
    DEF_VALET_PICK_ONE_VALID_SLOT_RS = int(DEF_RPC_NPC_VALET_SLOT_INFO_BASE + 6),

    // 查询槽位类型列表
    DEF_QUERY_VALET_SLOTINFO_LIST_RQ = int(DEF_RPC_NPC_VALET_SLOT_INFO_BASE + 7),
    DEF_QUERY_VALET_SLOTINFO_LIST_RS = int(DEF_RPC_NPC_VALET_SLOT_INFO_BASE + 8),

    //权限相关
    DEF_USER_PRIVILEGE_RQ = int(DEF_USER_PRIVILEGE_BASE + 0),
    DEF_USER_PRIVILEGE_RS = int(DEF_USER_PRIVILEGE_BASE + 1),

    DEF_SET_USER_SYS_PRIVILEGE_ID = int(DEF_USER_PRIVILEGE_BASE + 2),
    DEF_SET_USER_CHATBAR_PRIVILEGE_ID = int(DEF_USER_PRIVILEGE_BASE + 3),
    DEF_SET_USER_FAMILY_PRIVILEGE_ID = int(DEF_USER_PRIVILEGE_BASE + 4),
    DEF_SET_USER_DYNAMIC_PRIVILEGE_ID = int(DEF_USER_PRIVILEGE_BASE + 5),

    DEF_USER_FUNCTION_PRIVI_QUERY_RQ = int(DEF_USER_PRIVILEGE_BASE + 6),
    DEF_USER_FUNCTION_PRIVI_QUERY_RS = int(DEF_USER_PRIVILEGE_BASE + 7),

    // 扣减特权项计数
    DEF_USER_REDUCE_PRIVI_COUNT_RQ = int(DEF_USER_PRIVILEGE_BASE + 8),
    DEF_USER_REDUCE_PRIVI_COUNT_RS = int(DEF_USER_PRIVILEGE_BASE + 9),

    // 查询特权项计数
    DEF_USER_QRY_PRIVI_COUNT_RQ = int(DEF_USER_PRIVILEGE_BASE + 10),
    DEF_USER_QRY_PRIVI_COUNT_RS = int(DEF_USER_PRIVILEGE_BASE + 11),

    //再有新服务划分包定义区间避免冲突
    //切服相关请求包区间 定义为DEF_DEFAULT_RPC_PACKET_BASE + 1000  --- DEF_DEFAULT_RPC_PACKET_BASE + 1100
    DEF_ADMIN_MIGRATION_USER_RQ = int(DEF_USER_MIGRATION_BASE + 0),  // 后台给用户切服
    DEF_ADMIN_MIGRATION_USER_RS = int(DEF_USER_MIGRATION_BASE + 1),

    DEF_USER_PRPARE_MIGRATION_RQ = int(DEF_USER_MIGRATION_BASE + 2),
    DEF_USER_PRPARE_MIGRATION_RS = int(DEF_USER_MIGRATION_BASE + 3),

    DEF_USER_MIGRATION_LOADDATA_RQ = int(DEF_USER_MIGRATION_BASE + 4),
    DEF_USER_MIGRATION_LOADDATA_RS = int(DEF_USER_MIGRATION_BASE + 5),

    DEF_USER_MIGRATION_SAVEDATA_RQ = int(DEF_USER_MIGRATION_BASE + 6),
    DEF_USER_MIGRATION_SAVEDATA_RS = int(DEF_USER_MIGRATION_BASE + 7),

    DEF_USER_MIGRATION_COMPLETE_RQ = int(DEF_USER_MIGRATION_BASE + 8),
    DEF_USER_MIGRATION_COMPLETE_RS = int(DEF_USER_MIGRATION_BASE + 9),

    DEF_INTERNAL_CLEAN_USER_CACHE_DATA_RQ = int(DEF_USER_MIGRATION_BASE + 10),
    DEF_INTERNAL_CLEAN_USER_CACHE_DATA_RS = int(DEF_USER_MIGRATION_BASE + 11),

    DEF_QUERY_USER_SECTION_RQ = int(DEF_USER_MIGRATION_BASE + 12),
    DEF_QUERY_USER_SECTION_RS = int(DEF_USER_MIGRATION_BASE + 13),

    DEF_CHANGE_USER_SECTION_RQ = int(DEF_USER_MIGRATION_BASE + 14),
    DEF_CHANGE_USER_SECTION_RS = int(DEF_USER_MIGRATION_BASE + 15),

    DEF_QUERY_USER_SECTION_MUTL_RQ = int(DEF_USER_MIGRATION_BASE + 16),
    DEF_QUERY_USER_SECTION_MUTL_RS = int(DEF_USER_MIGRATION_BASE + 17),

    DEF_ADMIN_ADD_USER_MONEY_RQ = int(DEF_USER_MIGRATION_BASE + 18),  //后台给用户加钱
    DEF_ADMIN_ADD_USER_MONEY_RS = int(DEF_USER_MIGRATION_BASE + 19),

    DEF_ADMIN_ADD_USER_GOODS_RQ = int(DEF_USER_MIGRATION_BASE + 20),  //后台给用户加物品
    DEF_ADMIN_ADD_USER_GOODS_RS = int(DEF_USER_MIGRATION_BASE + 21),

    DEF_MIGRATION_CONTROL_RQ = int(DEF_USER_MIGRATION_BASE + 22),  // 切服服务控制接口
    DEF_MIGRATION_CONTROL_RS = int(DEF_USER_MIGRATION_BASE + 23),
    
    DEF_USER_MIGRATION_COST_RPC_RQ = int(DEF_USER_MIGRATION_BASE + 24), 
	DEF_USER_MIGRATION_COST_RPC_RS = int(DEF_USER_MIGRATION_BASE + 25),

    //用户道具，等级，车辆相关rpc 使用区间 定义为DEF_DEFAULT_RPC_PACKET_BASE + 1100  --- DEF_DEFAULT_RPC_PACKET_BASE + 1200
    DEF_SVR_ADD_USER_SKILL_ITEM_RQ = int(DEF_USER_GOODS_BASE + 0),
    DEF_SVR_ADD_USER_SKILL_ITEM_RS = int(DEF_USER_GOODS_BASE + 1),

    DEF_SVR_GET_USER_SKILL_ITEM_RQ = int(DEF_USER_GOODS_BASE + 2),
    DEF_SVR_GET_USER_SKILL_ITEM_RS = int(DEF_USER_GOODS_BASE + 3),

    DEF_SVR_CONSUME_USER_SKILL_ITEM_RQ = int(DEF_USER_GOODS_BASE + 4),
    DEF_SVR_CONSUME_USER_SKILL_ITEM_RS = int(DEF_USER_GOODS_BASE + 5),

    DEF_SVR_GET_USER_LEVEL_RQ = int(DEF_USER_GOODS_BASE + 6),
    DEF_SVR_GET_USER_LEVEL_RS = int(DEF_USER_GOODS_BASE + 7),

    DEF_SVR_SET_USER_LEVEL_RQ = int(DEF_USER_GOODS_BASE + 8),
    DEF_SVR_SET_USER_LEVEL_RS = int(DEF_USER_GOODS_BASE + 9),

    DEF_SVR_ADD_USER_EXPERIENCE_RQ = int(DEF_USER_GOODS_BASE + 10),
    DEF_SVR_ADD_USER_EXPERIENCE_RS = int(DEF_USER_GOODS_BASE + 11),

    DEF_SVR_GET_USER_LEVEL_GRADIENT_RQ = int(DEF_USER_GOODS_BASE + 12),
    DEF_SVR_GET_USER_LEVEL_GRADIENT_RS = int(DEF_USER_GOODS_BASE + 13),

    //新手引导
    DEF_SVR_GET_NEWCOMER_GUIDE_RQ = int(DEF_USER_GOODS_BASE + 14),
    DEF_SVR_GET_NEWCOMER_GUIDE_RS = int(DEF_USER_GOODS_BASE + 15),

    DEF_SVR_CHANGE_NEWCOMER_GUIDE_RQ = int(DEF_USER_GOODS_BASE + 16),
    DEF_SVR_CHANGE_NEWCOMER_GUIDE_RS = int(DEF_USER_GOODS_BASE + 17),

    DEF_SVR_SUB_USER_EXPERIENCE_RQ = int(DEF_USER_GOODS_BASE + 18),
    DEF_SVR_SUB_USER_EXPERIENCE_RS = int(DEF_USER_GOODS_BASE + 19),

    //技能等级 分服
    DEF_SVR_USER_SKILL_LEVEL_RQ = int(DEF_USER_GOODS_BASE + 20),
    DEF_SVR_USER_SKILL_LEVEL_RS = int(DEF_USER_GOODS_BASE + 21),

    //服装
    DEF_SVR_ADD_USER_DRESS_RQ = int(DEF_USER_DRESS_BASE + 0),
    DEF_SVR_ADD_USER_DRESS_RS = int(DEF_USER_DRESS_BASE + 1),

    DEF_SVR_SET_USER_DRESS_RQ = int(DEF_USER_DRESS_BASE + 2),
    DEF_SVR_SET_USER_DRESS_RS = int(DEF_USER_DRESS_BASE + 3),

    DEF_SVR_GET_USER_DRESS_RQ = int(DEF_USER_DRESS_BASE + 4),
    DEF_SVR_GET_USER_DRESS_RS = int(DEF_USER_DRESS_BASE + 5),


    DEF_SVR_ADD_USER_ACCESSORY_RQ = int(DEF_USER_DRESS_BASE + 10),
    //    DEF_SVR_ADD_USER_ACCESSORY_RS = int(DEF_USER_DRESS_BASE + 11),

    DEF_SVR_DEL_USER_ACCESSORY_RQ = int(DEF_USER_DRESS_BASE + 12),
    //    DEF_SVR_DEL_USER_ACCESSORY_RS = int(DEF_USER_DRESS_BASE + 13),

    DEF_SVR_GET_USER_ACCESSORY_RQ = int(DEF_USER_DRESS_BASE + 14),
    DEF_SVR_GET_USER_ACCESSORY_RS = int(DEF_USER_DRESS_BASE + 15),

    //车部件
    DEF_SVR_ADD_USER_COMPONENT_RQ = int(DEF_USER_COMPONENT_BASE + 0),
    //DEF_SVR_ADD_USER_COMPONENT_RS = int(DEF_USER_COMPONENT_BASE + 1),

    DEF_SVR_DEL_USER_COMPONENT_RQ = int(DEF_USER_COMPONENT_BASE + 2),
    //DEF_SVR_DEL_USER_COMPONENT_RS = int(DEF_USER_COMPONENT_BASE + 3),

    DEF_SVR_GET_USER_COMPONENT_RQ = int(DEF_USER_COMPONENT_BASE + 4),
    DEF_SVR_GET_USER_COMPONENT_RS = int(DEF_USER_COMPONENT_BASE + 5),

    //背景
    DEF_SVR_ADD_USER_SCENERY_RQ = int(DEF_USER_SCENERY_BASE + 0),
    //    DEF_SVR_ADD_USER_SCENERY_RS = int(DEF_USER_SCENERY_BASE + 1),

    DEF_SVR_SET_USER_SCENERY_RQ = int(DEF_USER_SCENERY_BASE + 2),
    //    DEF_SVR_SET_USER_SCENERY_RS = int(DEF_USER_SCENERY_BASE + 3),

    DEF_SVR_GET_USER_SCENERY_RQ = int(DEF_USER_SCENERY_BASE + 4),
    DEF_SVR_GET_USER_SCENERY_RS = int(DEF_USER_SCENERY_BASE + 5),

    //气泡
    DEF_SVR_ADD_USER_BUBBLE_RQ = int(DEF_USER_BUBBLE_BASE + 0),

    DEF_SVR_SET_USER_BUBBLE_RQ = int(DEF_USER_BUBBLE_BASE + 2),

    DEF_SVR_GET_USER_BUBBLE_RQ = int(DEF_USER_BUBBLE_BASE + 4),
    DEF_SVR_GET_USER_BUBBLE_RS = int(DEF_USER_BUBBLE_BASE + 5),


    // rpc 管理接口
    DEF_RPC_SVR_HUB_REG_RQ = int(DEF_RPC_MANAGEMENT_BASE + 0),

    //  清除缓存和数据用接口类型
    DEF_SVR_DEL_USER_ACHIVE_INFO_CACHE_RQ = int(DEF_RPC_MANAGEMENT_BASE + 1),     // 清除用户成就信息缓存
    DEF_SVR_DEL_USER_ACHIVE_INFO_CACHE_RS = int(DEF_RPC_MANAGEMENT_BASE + 2),

    DEF_SVR_DEL_USER_ACHIVE_AWARD_CACHE_RQ = int(DEF_RPC_MANAGEMENT_BASE + 3),    // 清除用户成就状态缓存
    DEF_SVR_DEL_USER_ACHIVE_AWARD_CACHE_RS = int(DEF_RPC_MANAGEMENT_BASE + 4),

    // 小跟班游戏DBCS接口
    DEF_GET_VALET_PROPERTY_RQ       = int(DEF_GAME_VALET_BASE + 0), // 获取跟班属性数据
    DEF_GET_VALET_PROPERTY_RS       = int(DEF_GAME_VALET_BASE + 1),
    DEF_GET_USER_VALET_COUNT_RQ     = int(DEF_GAME_VALET_BASE + 2), // 获取用户跟班数量
    DEF_GET_USER_VALET_COUNT_RS     = int(DEF_GAME_VALET_BASE + 3),
    DEF_GET_USER_VALET_INFO_RQ      = int(DEF_GAME_VALET_BASE + 4), // 获取用户单个跟班信息
    DEF_GET_USER_VALET_INFO_RS      = int(DEF_GAME_VALET_BASE + 5),
    DEF_GET_USER_VALET_INFO_LIST_RQ = int(DEF_GAME_VALET_BASE + 6), // 获取用户跟班列表信息
    DEF_GET_USER_VALET_INFO_LIST_RS = int(DEF_GAME_VALET_BASE + 7),
    DEF_GET_USER_VALET_HOST_RQ      = int(DEF_GAME_VALET_BASE + 8), // 获取用户主人
    DEF_GET_USER_VALET_HOST_RS      = int(DEF_GAME_VALET_BASE + 9),

    DEF_VALET_CREATE_RELATION_RQ         = int(DEF_GAME_VALET_BASE + 10), // 建立跟班关系
    DEF_VALET_CREATE_RELATION_RS         = int(DEF_GAME_VALET_BASE + 11),
    DEF_VALET_RESET_SLOT_INDEX_RQ        = int(DEF_GAME_VALET_BASE + 12), // 调整跟班槽位
    DEF_VALET_RESET_SLOT_INDEX_RS        = int(DEF_GAME_VALET_BASE + 13),
    DEF_VALET_RELIEVE_RELATION_RQ        = int(DEF_GAME_VALET_BASE + 14), // 解除跟班关系
    DEF_VALET_RELIEVE_RELATION_RS        = int(DEF_GAME_VALET_BASE + 15),
    DEF_GET_USER_VALET_LIST_FILTER_RQ    = int(DEF_GAME_VALET_BASE + 16), // 获取过滤后的跟班列表
    DEF_GET_USER_VALET_LIST_FILTER_RS    = int(DEF_GAME_VALET_BASE + 17),
    DEF_GET_USER_IMPRISON_VALET_RQ       = int(DEF_GAME_VALET_BASE + 18), // 获取用户被囚禁跟班
    DEF_GET_USER_IMPRISON_VALET_RS       = int(DEF_GAME_VALET_BASE + 19),

    DEF_USER_VALET_STATUS_CHG_RQ      = int(DEF_GAME_VALET_BASE + 50), // 跟班虚弱状态变化
    DEF_USER_VALET_STATUS_CHG_RS      = int(DEF_GAME_VALET_BASE + 51),
    DEF_USER_VALET_QUALITY_CHG_RQ     = int(DEF_GAME_VALET_BASE + 52), // 跟班品质变化
    DEF_USER_VALET_QUALITY_CHG_RS     = int(DEF_GAME_VALET_BASE + 53),
    DEF_VALET_TASK_EVENT_BEGIN_RQ     = int(DEF_GAME_VALET_BASE + 54), // 跟班事件开始触发
    DEF_VALET_TASK_EVENT_BEGIN_RS     = int(DEF_GAME_VALET_BASE + 55),
    DEF_USER_VALET_TOUCH_EVENT_END_RQ = int(DEF_GAME_VALET_BASE + 56), // 立即开宝箱付费接口
    DEF_USER_VALET_TOUCH_EVENT_END_RS = int(DEF_GAME_VALET_BASE + 57),
    DEF_USER_IMPRISON_STATUS_CHG_RQ   = int(DEF_GAME_VALET_BASE + 58), // 用户囚禁状态变化
    DEF_USER_IMPRISON_STATUS_CHG_RS   = int(DEF_GAME_VALET_BASE + 59),

    DEF_GET_OTHER_USER_VALET_INFO_RQ     = int(DEF_GAME_VALET_BASE + 60), // 获取他人跟班信息
    DEF_GET_OTHER_USER_VALET_INFO_RS     = int(DEF_GAME_VALET_BASE + 61),
    DEF_CLI_USER_VALET_OPEN_AWARD_RQ     = int(DEF_GAME_VALET_BASE + 62), // 客户端打开奖励信息
    DEF_CLI_USER_VALET_OPEN_AWARD_RS     = int(DEF_GAME_VALET_BASE + 63),
    //DEF_CLI_VALET_CREATE_RELATION_RQ     = int(DEF_GAME_VALET_BASE + 64), // 客户端建立跟班关系(已废弃)
    //DEF_CLI_VALET_CREATE_RELATION_RS     = int(DEF_GAME_VALET_BASE + 65),
    //DEF_CLI_VALET_RELIEVE_RELATION_RQ    = int(DEF_GAME_VALET_BASE + 66), // 客户端解除跟班关系(已废弃)
    //DEF_CLI_VALET_RELIEVE_RELATION_RS    = int(DEF_GAME_VALET_BASE + 67),
    DEF_VALET_CREATE_RELATION_MULTIPLE_RQ  = int(DEF_GAME_VALET_BASE + 64), // 批量建立跟班关系
    DEF_VALET_CREATE_RELATION_MULTIPLE_RS  = int(DEF_GAME_VALET_BASE + 65),
    DEF_VALET_RELIEVE_RELATION_MULTIPLE_RQ = int(DEF_GAME_VALET_BASE + 66), // 批量解除跟班关系
    DEF_VALET_RELIEVE_RELATION_MULTIPLE_RS = int(DEF_GAME_VALET_BASE + 67),
    DEF_USER_VALET_RELATION_CHG_RQ       = int(DEF_GAME_VALET_BASE + 68), // 跟班关系变化通知
    DEF_USER_VALET_RELATION_CHG_RS       = int(DEF_GAME_VALET_BASE + 69),

    DEF_USER_VALET_OPEN_AWARD_RQ           = int(DEF_GAME_VALET_BASE + 70), // 用户打开奖励
    DEF_USER_VALET_OPEN_AWARD_RS           = int(DEF_GAME_VALET_BASE + 71),
    DEF_USER_VALET_RECV_AWARD_RQ           = int(DEF_GAME_VALET_BASE + 72), // 用户领取奖励
    DEF_USER_VALET_RECV_AWARD_RS           = int(DEF_GAME_VALET_BASE + 73),
    //DEF_USER_VALET_LOOT_AWARD_PK_RESULT_RQ = int(DEF_GAME_VALET_BASE + 76), // 顺东西PK结果
    //DEF_USER_VALET_LOOT_AWARD_PK_RESULT_RS = int(DEF_GAME_VALET_BASE + 77),
    DEF_RESET_USER_VALET_AWARD_RQ          = int(DEF_GAME_VALET_BASE + 76), // 重置用户跟班奖励 复用 “顺东西PK结果”
    DEF_RESET_USER_VALET_AWARD_RS          = int(DEF_GAME_VALET_BASE + 77),
    DEF_USER_VALET_LOOT_AWARD_RQ           = int(DEF_GAME_VALET_BASE + 78), // 用户顺奖励
    DEF_USER_VALET_LOOT_AWARD_RS           = int(DEF_GAME_VALET_BASE + 79),

    DEF_USER_VALET_KEEPER_COLLECT_AWARD_RQ = int(DEF_GAME_VALET_BASE + 80), // 管家收集已掉落奖励
    DEF_USER_VALET_KEEPER_COLLECT_AWARD_RS = int(DEF_GAME_VALET_BASE + 81),
    DEF_GET_VALET_KEEPER_AWARD_LIST_RQ     = int(DEF_GAME_VALET_BASE + 82), // 获取管家领取奖励列表
    DEF_GET_VALET_KEEPER_AWARD_LIST_RS     = int(DEF_GAME_VALET_BASE + 83),
    DEF_USER_VALET_RECV_KEEPER_AWARD_RQ    = int(DEF_GAME_VALET_BASE + 84), // 领取管家奖励
    DEF_USER_VALET_RECV_KEEPER_AWARD_RS    = int(DEF_GAME_VALET_BASE + 85),
    //DEF_USER_VALET_CONSUME_RQ              = int(DEF_GAME_VALET_BASE + 86), // 用户跟班其他功能扣费
    //DEF_USER_VALET_CONSUME_RS              = int(DEF_GAME_VALET_BASE + 87),
    DEF_RESTORE_USER_VALET_AWARD_RQ        = int(DEF_GAME_VALET_BASE + 86), // 恢复用户跟班奖励
    DEF_RESTORE_USER_VALET_AWARD_RS        = int(DEF_GAME_VALET_BASE + 87),
    DEF_VL_PROPERTY_QUERY_RQ               = int(DEF_GAME_VALET_BASE + 88), // 用户属性查询
    DEF_VL_PROPERTY_QUERY_RS               = int(DEF_GAME_VALET_BASE + 89),

    DEF_USER_VALET_COUNT_CHANGE_RQ         = int(DEF_GAME_VALET_BASE + 90), // 用户跟班数量变化
    DEF_USER_VALET_COUNT_CHANGE_RS         = int(DEF_GAME_VALET_BASE + 91),
    DEF_CLI_GET_VALET_PROPERTY_RQ          = int(DEF_GAME_VALET_BASE + 92), // 客户端获取跟班属性接口
    DEF_CLI_GET_VALET_PROPERTY_RS          = int(DEF_GAME_VALET_BASE + 93),
    DEF_GET_OTHER_USER_VALET_STATUS_RQ     = int(DEF_GAME_VALET_BASE + 94), // 查看别人跟班奖励状态
    DEF_GET_OTHER_USER_VALET_STATUS_RS     = int(DEF_GAME_VALET_BASE + 95), // 查看别人跟班奖励状态

    // valet_data_center
    DEF_VL_GOODS_PROFILE_RQ     = int(DEF_GAME_VALET_BASE + 74), // 获取跟班游戏数据
    DEF_VL_GOODS_PROFILE_RS     = int(DEF_GAME_VALET_BASE + 75),

    // 20~49 预留给valet_main使用
    DEF_VLUNLINK_RQ             = int(DEF_GAME_VALET_BASE + 26), // 解除跟班关系
    DEF_VLUNLINK_RS             = int(DEF_GAME_VALET_BASE + 27),
    DEF_VLGETPRICEWEIGHT_RQ     = int(DEF_GAME_VALET_BASE + 28), // 查询跟班身价状态
    DEF_VLGETPRICEWEIGHT_RS     = int(DEF_GAME_VALET_BASE + 29),
    DEF_VLGETPRICEWEIGHTLIST_RQ = int(DEF_GAME_VALET_BASE + 30), // 查询跟班身价状态
    DEF_VLGETPRICEWEIGHTLIST_RS = int(DEF_GAME_VALET_BASE + 31),
    DEF_VLDOMMSDAYCLEAR_RQ      = int(DEF_GAME_VALET_BASE + 32), // 清除跟班数据
    DEF_VLDOMMSDAYCLEAR_RS      = int(DEF_GAME_VALET_BASE + 33),
    DEF_PUSHVLPRICEFACTOR_RQ    = int(DEF_GAME_VALET_BASE + 34), // 推送小跟班身价因子
    DEF_PUSHVLPRICEFACTOR_RS    = int(DEF_GAME_VALET_BASE + 35),
    DEF_GETVLABILITYPRICE_RQ    = int(DEF_GAME_VALET_BASE + 38), // 获取小跟班能力值和身价
    DEF_GETVLABILITYPRICE_RS    = int(DEF_GAME_VALET_BASE + 39),
    DEF_VFGETVALETRELEATION_RQ  = int(DEF_GAME_VALET_BASE + 40), // 战斗前获取跟班关系数据
    DEF_VFGETVALETRELEATION_RS  = int(DEF_GAME_VALET_BASE + 41),
    DEF_VFVALETFIGHTFINISH_RQ   = int(DEF_GAME_VALET_BASE + 42), // 战斗结束后反馈
    DEF_VFVALETFIGHTFINISH_RS   = int(DEF_GAME_VALET_BASE + 43),


    // 跟班槽位奖励接口定义
    DEF_GET_USER_VALET_SLOT_AWARD_INFO_RQ       = int(DEF_RPC_VALET_SLOT_AWARD_BASE + 0), // 获取跟班槽位奖励信息
    DEF_GET_USER_VALET_SLOT_AWARD_INFO_RS       = int(DEF_RPC_VALET_SLOT_AWARD_BASE + 1),
    DEF_RECV_USER_VALET_SLOT_AWARD_RQ           = int(DEF_RPC_VALET_SLOT_AWARD_BASE + 2), // 领取跟班槽位奖励信息
    DEF_RECV_USER_VALET_SLOT_AWARD_RS           = int(DEF_RPC_VALET_SLOT_AWARD_BASE + 3),
    DEF_GET_OTHER_VALET_SLOT_AWARD_INFO_RQ      = int(DEF_RPC_VALET_SLOT_AWARD_BASE + 4), // 获取他人跟班槽位奖励信息
    DEF_GET_OTHER_VALET_SLOT_AWARD_INFO_RS      = int(DEF_RPC_VALET_SLOT_AWARD_BASE + 5),
    DEF_LOOT_USER_VALET_SLOT_AWARD_RQ           = int(DEF_RPC_VALET_SLOT_AWARD_BASE + 6), // 抢他人跟班槽位奖励
    DEF_LOOT_USER_VALET_SLOT_AWARD_RS           = int(DEF_RPC_VALET_SLOT_AWARD_BASE + 7),
    DEF_GET_SELECT_VALET_SLOT_AWARD_INFO_RQ     = int(DEF_RPC_VALET_SLOT_AWARD_BASE + 8), // 获取可选跟班槽位奖励信息
    DEF_GET_SELECT_VALET_SLOT_AWARD_INFO_RS     = int(DEF_RPC_VALET_SLOT_AWARD_BASE + 9),
    DEF_LOOT_VALET_SLOT_AWARD_SELECT_RQ         = int(DEF_RPC_VALET_SLOT_AWARD_BASE + 10), // 抢跟班槽位奖励选择
    DEF_LOOT_VALET_SLOT_AWARD_SELECT_RS         = int(DEF_RPC_VALET_SLOT_AWARD_BASE + 11),
    DEF_GET_OTHER_VALET_SLOT_AWARD_INFO_LIST_RQ = int(DEF_RPC_VALET_SLOT_AWARD_BASE + 12), // 批量获取他人跟班槽位奖励信息
    DEF_GET_OTHER_VALET_SLOT_AWARD_INFO_LIST_RS = int(DEF_RPC_VALET_SLOT_AWARD_BASE + 13),
    DEF_USER_VALET_SLOT_RELATION_CHANGE_RQ      = int(DEF_RPC_VALET_SLOT_AWARD_BASE + 14), // 用户跟班关系变化通知
    DEF_USER_VALET_SLOT_RELATION_CHANGE_RS      = int(DEF_RPC_VALET_SLOT_AWARD_BASE + 15),
    DEF_USER_LOOT_SLOT_AWARD_FAILED_RQ          = int(DEF_RPC_VALET_SLOT_AWARD_BASE + 18), // 抢夺槽位奖励失败
    DEF_USER_LOOT_SLOT_AWARD_FAILED_RS          = int(DEF_RPC_VALET_SLOT_AWARD_BASE + 19),
    DEF_USER_VALET_SLOT_WEAK_CHG_RQ             = int(DEF_RPC_VALET_SLOT_AWARD_BASE + 20), // 跟班虚弱变化通知
    DEF_USER_VALET_SLOT_WEAK_CHG_RS             = int(DEF_RPC_VALET_SLOT_AWARD_BASE + 21),
    DEF_QUERY_VALET_REGISTER_INVITE_RQ          = int(DEF_RPC_VALET_SLOT_AWARD_BASE + 22), // 查询跟班注册邀请RQ
    DEF_QUERY_VALET_REGISTER_INVITE_RS          = int(DEF_RPC_VALET_SLOT_AWARD_BASE + 23),
    DEF_USER_VALET_SLOT_IMPRISON_CHANGE_RQ      = int(DEF_RPC_VALET_SLOT_AWARD_BASE + 24), // 用户跟班囚禁变化通知
    DEF_USER_VALET_SLOT_IMPRISON_CHANGE_RS      = int(DEF_RPC_VALET_SLOT_AWARD_BASE + 25),
    DEF_USER_VALET_SLOT_INVITE_REGISTER_RQ      = int(DEF_RPC_VALET_SLOT_AWARD_BASE + 26), // 用户邀请注册通知
    DEF_USER_VALET_SLOT_INVITE_REGISTER_RS      = int(DEF_RPC_VALET_SLOT_AWARD_BASE + 27),
    DEF_RESTORE_USER_VALET_SLOT_AWARD_RQ        = int(DEF_RPC_VALET_SLOT_AWARD_BASE + 28), // 恢复用户槽位奖励
    DEF_RESTORE_USER_VALET_SLOT_AWARD_RS        = int(DEF_RPC_VALET_SLOT_AWARD_BASE + 29),
	DEF_GET_ROBOT_VALET_SLOT_AWARD_INFO_LIST_RQ = int(DEF_RPC_VALET_SLOT_AWARD_BASE + 30), // 批量获取机器人跟班槽位奖励信息
	DEF_GET_ROBOT_VALET_SLOT_AWARD_INFO_LIST_RS = int(DEF_RPC_VALET_SLOT_AWARD_BASE + 31),
	DEF_GET_ROBOT_SELECT_VALET_SLOT_AWARD_INFO_RQ = int(DEF_RPC_VALET_SLOT_AWARD_BASE + 32), // 获取机器人可选跟班槽位奖励信息
	DEF_GET_ROBOT_SELECT_VALET_SLOT_AWARD_INFO_RS = int(DEF_RPC_VALET_SLOT_AWARD_BASE + 33),

    // 用户金钱相关接口定义
    DEF_GET_USER_ALL_MONEY_RQ     = int(DEF_MONEY_BASE + 0),             // 查询用户金钱余额
    DEF_GET_USER_ALL_MONEY_RS     = int(DEF_MONEY_BASE + 1),
    DEF_TCP_GET_USER_ALL_MONEY_RQ = int(DEF_MONEY_BASE + 2),             // TCP包查询用户金钱余额
    DEF_TCP_GET_USER_ALL_MONEY_RS = int(DEF_MONEY_BASE + 3),

    // 用户豆相关接口定义
    DEF_GET_USER_BEAN_RQ          = int(DEF_MONEY_BASE + 4),             // 获取用户豆余额
    DEF_GET_USER_BEAN_RS          = int(DEF_MONEY_BASE + 5),
    DEF_CHARGE_USER_BEAN_RQ       = int(DEF_MONEY_BASE + 6),             // 用户豆充值
    DEF_CHARGE_USER_BEAN_RS       = int(DEF_MONEY_BASE + 7),
    DEF_CONSUME_USER_BEAN_RQ      = int(DEF_MONEY_BASE + 8),             // 用户豆消费
    DEF_CONSUME_USER_BEAN_RS      = int(DEF_MONEY_BASE + 9),
    DEF_EXCHANGE_USER_BEAN_RQ     = int(DEF_MONEY_BASE + 10),            // 用户豆兑换
    DEF_EXCHANGE_USER_BEAN_RS     = int(DEF_MONEY_BASE + 11),

    DEF_TCP_GET_USER_VALET_PROPERTY_RQ = int(DEF_MONEY_BASE + 12),       // TCP包查询用户跟班属性
    DEF_TCP_GET_USER_VALET_PROPERTY_RS = int(DEF_MONEY_BASE + 13),

    // RMB相关接口定义
    DEF_GET_USER_RMB_RQ                     = int(DEF_MONEY_BASE + 12),             // 获取用户RMB余额
    DEF_GET_USER_RMB_RS                     = int(DEF_MONEY_BASE + 13),
    DEF_CHARGE_USER_RMB_RQ                  = int(DEF_MONEY_BASE + 14),             // 用户RMB充值
    DEF_CHARGE_USER_RMB_RS                  = int(DEF_MONEY_BASE + 15),
    DEF_CONSUME_USER_RMB_RQ                 = int(DEF_MONEY_BASE + 16),             // 用户RMB消费
    DEF_CONSUME_USER_RMB_RS                 = int(DEF_MONEY_BASE + 17),
    DEF_EXCHANGE_USER_RMB_FOR_DIAMOND_RQ    = int(DEF_MONEY_BASE + 18),            // 用户RMB兑换钻石
    DEF_EXCHANGE_USER_RMB_FOR_DIAMOND_RS    = int(DEF_MONEY_BASE + 19),

    DEF_SUBSCRIBE_USER_BEAN_RQ     = int(DEF_MONEY_BASE + 20),            //红包，道具推荐订阅
    DEF_SUBSCRIBE_USER_BEAN_RS     = int(DEF_MONEY_BASE + 21),

    DEF_RED_PACKET_SUB_MONEY_RQ     = int(DEF_MONEY_BASE + 22),            //红包掉落从池子扣钱
    DEF_RED_PACKET_SUB_MONEY_RS     = int(DEF_MONEY_BASE + 23),

    DEF_GET_USER_RMB_WEIGHT_RQ      = int(DEF_MONEY_BASE + 24),             // RMB权重查询
    DEF_GET_USER_RMB_WEIGHT_RS      = int(DEF_MONEY_BASE + 25),

    DEF_GET_USER_RMB_CONSUME_SUMMARY_RQ = int(DEF_MONEY_BASE + 26),         // RMB 消费统计
    DEF_GET_USER_RMB_CONSUME_SUMMARY_RS = int(DEF_MONEY_BASE + 27),

    DEF_UPDATE_USER_RMB_CACHE_RQ = int(DEF_MONEY_BASE + 28),                // 更新RMB缓存
    DEF_UPDATE_USER_RMB_CACHE_RS = int(DEF_MONEY_BASE + 29),

    DEF_STEAL_RED_PACKET_SUB_MONEY_RQ     = int(DEF_MONEY_BASE + 30),       //红包掉落从池子扣钱  偷红包使用
    DEF_STEAL_RED_PACKET_SUB_MONEY_RS     = int(DEF_MONEY_BASE + 31),

    DEF_GAME_RED_PACKET_SUB_MONEY_RQ     = int(DEF_MONEY_BASE + 32),            //游戏从池子扣钱
    DEF_GAME_RED_PACKET_SUB_MONEY_RS     = int(DEF_MONEY_BASE + 33),

    DEF_GET_USER_DIAMOND_MONEY_RQ     = int(DEF_MONEY_BASE + 34),             // 查询用户钻石余额
    DEF_GET_USER_DIAMOND_MONEY_RS     = int(DEF_MONEY_BASE + 35),

    DEF_GAME_RED_PACKET_SUB_MONEY_ITEMS_RQ     = int(DEF_MONEY_BASE + 36),            //游戏从池子扣钱  批量扣钱
    DEF_GAME_RED_PACKET_SUB_MONEY_ITEMS_RS     = int(DEF_MONEY_BASE + 37),

	DEF_GAME_RICH_RED_PACKET_SUB_MONEY_RQ     = int(DEF_MONEY_BASE + 38),            //土豪红包从池子扣钱  
	DEF_GAME_RICH_RED_PACKET_SUB_MONEY_RS     = int(DEF_MONEY_BASE + 39),

	DEF_GAME_RICH_RED_PACKET_SUB_BIG_MONEY_RQ     = int(DEF_MONEY_BASE + 40),            //土豪红包从池子扣大额红包
	DEF_GAME_RICH_RED_PACKET_SUB_BIG_MONEY_RS     = int(DEF_MONEY_BASE + 41),

	DEF_FIND_SISTER_RED_PACKET_SUB_BIG_MONEY_RQ     = int(DEF_MONEY_BASE + 42),            //找你妹从池子扣红包
	DEF_FIND_SISTER_RED_PACKET_SUB_BIG_MONEY_RS     = int(DEF_MONEY_BASE + 43),

	DEF_QUERY_NEW_USER_STEAL_RMB_COUNT_RQ     = int(DEF_MONEY_BASE + 44),            //查询新人红包次数 
	DEF_QUERY_NEW_USER_STEAL_RMB_COUNT_RS     = int(DEF_MONEY_BASE + 45),             

	DEF_REDUCE_NEW_USER_STEAL_RMB_COUNT_RQ     = int(DEF_MONEY_BASE + 46),             //扣除新人红包次数
	DEF_REDUCE_NEW_USER_STEAL_RMB_COUNT_RS     = int(DEF_MONEY_BASE + 47),

	DEF_REDUCE_RMB_TIMES_CHG_SYNC_RQ     	   = int(DEF_MONEY_BASE + 48),             //人民币次数变化同步消息
	DEF_REDUCE_RMB_TIMES_CLEAN_SYNC_RQ     	   = int(DEF_MONEY_BASE + 49),             //人民币次数清理同步消息

	DEF_REDUCE_FETCH_MONEY_RQ     				= int(DEF_MONEY_BASE + 50),             //php领钱
	DEF_REDUCE_FETCH_MONEY_RS     				= int(DEF_MONEY_BASE + 51),             //php领钱

    //
    DEF_RCCLEANCACHE_RQ = int(DEF_CONTROL_BASE + 0),
    DEF_RCCLEANCACHE_RS = int(DEF_CONTROL_BASE + 1),
    DEF_RCGETUSER_RQ = int(DEF_CONTROL_BASE + 2),
    DEF_RCGETUSER_RS = int(DEF_CONTROL_BASE + 3),
    DEF_RCSETUSER_RQ = int(DEF_CONTROL_BASE + 4),
    DEF_RCSETUSER_RS = int(DEF_CONTROL_BASE + 5),
    DEF_RCGETUSERBIN_RQ = int(DEF_CONTROL_BASE + 6),
    DEF_RCGETUSERBIN_RS = int(DEF_CONTROL_BASE + 7),

    //web端注册接口定义
    DEF_WEB_REGISTER_RQ = int(DEF_REGISTER_BASE + 1),
    DEF_WEB_REGISTER_RS = int(DEF_REGISTER_BASE + 2),

    DEF_QUERY_WITHDRAW_H5_OPEN_ID_RQ = int(DEF_REGISTER_BASE + 3),
    DEF_QUERY_WITHDRAW_H5_OPEN_ID_RS = int(DEF_REGISTER_BASE + 4),

    DEF_QUERY_WITHDRAW_PAIPAI_ID_2_UNION_ID_RQ = int(DEF_REGISTER_BASE + 5),
    DEF_QUERY_WITHDRAW_PAIPAI_ID_2_UNION_ID_RS = int(DEF_REGISTER_BASE + 6),

    //校验是否在app注册过
    DEF_CHECK_ACCOUNT_APP_REGISTER_RQ            =     int(DEF_REGISTER_BASE + 7),
    DEF_CHECK_ACCOUNT_APP_REGISTER_RS           =      int(DEF_REGISTER_BASE + 8),

    DEF_CHECK_ACCOUNT_RELEVANCY_RQ  =      int(DEF_REGISTER_BASE + 9),
    DEF_CHECK_ACCOUNT_RELEVANCY_RS  =      int(DEF_REGISTER_BASE + 10),

    //短信验证码获取
    DEF_SMS_VERIFY_CODE_QUERY_RPC_RQ  =      int(DEF_REGISTER_BASE + 11),
    DEF_SMS_VERIFY_CODE_QUERY_RPC_RS  =      int(DEF_REGISTER_BASE + 12),

    //短信验证码验证
    DEF_CHECK_SMS_VERIFY_CODE_RQ  =      int(DEF_REGISTER_BASE + 13),
    DEF_CHECK_SMS_VERIFY_CODE_RS  =      int(DEF_REGISTER_BASE + 14),

    //是否注册过
    DEF_CHECK_ACCOUNT_REGISTER_RQ  =      int(DEF_REGISTER_BASE + 15),
    DEF_CHECK_ACCOUNT_REGISTER_RS  =      int(DEF_REGISTER_BASE + 16),

    //完善资料
    DEF_WEB_USER_COMPLETE_INFO_RQ  =      int(DEF_REGISTER_BASE + 17),
    DEF_WEB_USER_COMPLETE_INFO_RS  =      int(DEF_REGISTER_BASE + 18),

    DEF_ACCOUNT_RELEVANCY_QUERY_RQ  =      int(DEF_REGISTER_BASE + 19),
    DEF_ACCOUNT_RELEVANCY_QUERY_RS  =      int(DEF_REGISTER_BASE + 20),

    // 影响力
    DEF_GETINFLUENCE_RQ = int(DEF_USER_INFLUENCE_BASE + 1),// 获取影响力请求
    DEF_GETINFLUENCE_RS = int(DEF_USER_INFLUENCE_BASE + 2),// 获取影响力返回

    DEF_ADDINFLUENCE_RQ = int(DEF_USER_INFLUENCE_BASE + 3),// 增加影响力请求
    DEF_ADDINFLUENCE_RS = int(DEF_USER_INFLUENCE_BASE + 4),// 增加影响力返回

    DEF_SUBINFLUENCE_RQ = int(DEF_USER_INFLUENCE_BASE + 5),// 减少影响力请求
    DEF_SUBINFLUENCE_RS = int(DEF_USER_INFLUENCE_BASE + 6),// 减少影响力返回

    DEF_UFISFRIEND_RQ = int(DEF_USER_FRIEND_BASE + 1),// 查询用户是否好友请求
    DEF_UFISFRIEND_RS = int(DEF_USER_FRIEND_BASE + 2),// 查询用户是否好友返回

    DEF_RPC_BATCH_QUERY_IS_FRIEND_RQ = int(DEF_USER_FRIEND_BASE + 3), // 批量查询好友关系请求
    DEF_RPC_BATCH_QUERY_IS_FRIEND_RS = int(DEF_USER_FRIEND_BASE + 4), // 批量查询好友关系应答

    DEF_RPC_USER_FRIEND_RQ = int(DEF_USER_FRIEND_BASE + 5), // 好友列表查询
    DEF_RPC_USER_FRIEND_RS = int(DEF_USER_FRIEND_BASE + 6), //
    DEF_RPC_USER_FRIEND_V2_RQ = int(DEF_USER_FRIEND_BASE + 7), // 好友列表查询
    DEF_RPC_USER_FRIEND_V2_RS = int(DEF_USER_FRIEND_BASE + 8), //

    DEF_RPC_USER_FRIEND_COUNT_RQ = int(DEF_USER_FRIEND_BASE + 9), // 好友数量查询
    DEF_RPC_USER_FRIEND_COUNT_RS = int(DEF_USER_FRIEND_BASE + 10), //
    DEF_RPC_USER_FRIEND_V3_RQ = int(DEF_USER_FRIEND_BASE + 11), // 好友查询
    DEF_RPC_USER_FRIEND_V3_RS = int(DEF_USER_FRIEND_BASE + 12), //

	DEF_RPC_USER_FRIEND_ONLINE_RQ = int(DEF_USER_FRIEND_BASE + 13), // 查询好友在线的请求包
	DEF_RPC_USER_FRIEND_ONLINE_RS = int(DEF_USER_FRIEND_BASE + 14), // 查询好友在线返回包
	
    /*-------------------------------跟班属性----------------------------------*/
    DEF_VPGETENERGYPOINT_RQ = int(DEF_GAME_VALET_PROPERTY + 1),// 获取用户体力请求
    DEF_VPGETENERGYPOINT_RS = int(DEF_GAME_VALET_PROPERTY + 2),// 获取用户体力返回

    DEF_VPADDENERGYPOINT_RQ = int(DEF_GAME_VALET_PROPERTY + 3),// 加用户体力请求
    DEF_VPADDENERGYPOINT_RS = int(DEF_GAME_VALET_PROPERTY + 4),// 加用户体力返回

    DEF_VPSUBENERGYPOINT_RQ = int(DEF_GAME_VALET_PROPERTY + 5),// 减用户体力请求
    DEF_VPSUBENERGYPOINT_RS = int(DEF_GAME_VALET_PROPERTY + 6),// 减用户体力返回

    DEF_VPGETFIGHTPOINT_RQ = int(DEF_GAME_VALET_PROPERTY + 7),// 获取用户战斗属性请求
    DEF_VPGETFIGHTPOINT_RS = int(DEF_GAME_VALET_PROPERTY + 8),// 获取用户战斗属性返回

    DEF_VPADDFIGHTCRTICALSTRIKEPOINT_RQ = int(DEF_GAME_VALET_PROPERTY +  9),// 加用户战斗属性(暴击率)请求
    DEF_VPADDFIGHTCRTICALSTRIKEPOINT_RS = int(DEF_GAME_VALET_PROPERTY + 10),// 加用户战斗属性(暴击率)返回

    DEF_VPSUBFIGHTCRTICALSTRIKEPOINT_RQ = int(DEF_GAME_VALET_PROPERTY + 11),// 减用户战斗属性(暴击率)请求
    DEF_VPSUBFIGHTCRTICALSTRIKEPOINT_RS = int(DEF_GAME_VALET_PROPERTY + 12),// 减用户战斗属性(暴击率)返回

    DEF_VPADDFIGHTDODGERATINGPOINT_RQ = int(DEF_GAME_VALET_PROPERTY + 13),// 加用户战斗属性(闪避率)请求
    DEF_VPADDFIGHTDODGERATINGPOINT_RS = int(DEF_GAME_VALET_PROPERTY + 14),// 加用户战斗属性(闪避率)返回

    DEF_VPSUBFIGHTDODGERATINGPOINT_RQ = int(DEF_GAME_VALET_PROPERTY + 15),// 减用户战斗属性(闪避率)请求
    DEF_VPSUBFIGHTDODGERATINGPOINT_RS = int(DEF_GAME_VALET_PROPERTY + 16),// 减用户战斗属性(闪避率)返回

    DEF_VPADDFIGHTFIGHTINGCAPACITYPOINT_RQ = int(DEF_GAME_VALET_PROPERTY + 17),// 加用户战斗属性(战斗力)请求
    DEF_VPADDFIGHTFIGHTINGCAPACITYPOINT_RS = int(DEF_GAME_VALET_PROPERTY + 18),// 加用户战斗属性(战斗力)返回

    DEF_VPSUBFIGHTFIGHTINGCAPACITYPOINT_RQ = int(DEF_GAME_VALET_PROPERTY + 19),// 减用户战斗属性(战斗力)请求
    DEF_VPSUBFIGHTFIGHTINGCAPACITYPOINT_RS = int(DEF_GAME_VALET_PROPERTY + 20),// 减用户战斗属性(战斗力)返回

    DEF_VPADVANCEFIGHTINGLEVEL_RQ = int(DEF_GAME_VALET_PROPERTY + 21),// 晋级(战斗阶数)请求
    DEF_VPADVANCEFIGHTINGLEVEL_RS = int(DEF_GAME_VALET_PROPERTY + 22),// 晋级(战斗阶数)返回
    // 道具
    DEF_GET_FIGHTING_GOODS_RQ = int(DEF_GAME_VALET_PROPERTY + 31),
    DEF_GET_FIGHTING_GOODS_RS = int(DEF_GAME_VALET_PROPERTY + 32),

    DEF_ADD_FIGHTING_GOODS_RQ = int(DEF_GAME_VALET_PROPERTY + 33),
    DEF_ADD_FIGHTING_GOODS_RS = int(DEF_GAME_VALET_PROPERTY + 34),

    DEF_CONSUME_FIGHTING_GOODS_RQ = int(DEF_GAME_VALET_PROPERTY + 35),
    DEF_CONSUME_FIGHTING_GOODS_RS = int(DEF_GAME_VALET_PROPERTY + 36),

    DEF_EXCHANGE_GOODS_FOR_ENERGY_RQ = int(DEF_GAME_VALET_PROPERTY + 37),
    DEF_EXCHANGE_GOODS_FOR_ENERGY_RS = int(DEF_GAME_VALET_PROPERTY + 38),

    DEF_BUY_FIGHTING_GOODS_RQ = int(DEF_GAME_VALET_PROPERTY + 39),
    DEF_BUY_FIGHTING_GOODS_RS = int(DEF_GAME_VALET_PROPERTY + 40),

    DEF_GET_COMBAT_ITEM_RQ = int(DEF_GAME_VALET_PROPERTY + 41),   // 客户端使用接口
    DEF_GET_COMBAT_ITEM_RS = int(DEF_GAME_VALET_PROPERTY + 42),

    // NPC 卡片
    DEF_GET_USER_NPC_CARD_RQ = int(DEF_GAME_VALET_PROPERTY + 43),   // 获取NPC卡片
    DEF_GET_USER_NPC_CARD_RS = int(DEF_GAME_VALET_PROPERTY + 44),

    DEF_ADD_USER_NPC_CARD_RQ = int(DEF_GAME_VALET_PROPERTY + 45),   // 增加NPC卡片
    DEF_ADD_USER_NPC_CARD_RS = int(DEF_GAME_VALET_PROPERTY + 46),

    DEF_SUB_USER_NPC_CARD_RQ = int(DEF_GAME_VALET_PROPERTY + 47),   // 减少NPC卡片
    DEF_SUB_USER_NPC_CARD_RS = int(DEF_GAME_VALET_PROPERTY + 48),

    //推荐事件获取
    DEF_EVENT_QUERY_RQ = int(DEF_GAME_VALET_PROPERTY + 49),
    DEF_EVENT_QUERY_RS = int(DEF_GAME_VALET_PROPERTY + 50),

    //用户装备，技能加成查询
    DEF_USER_ATTR_QUERY_RQ = int(DEF_GAME_VALET_PROPERTY + 51),
    DEF_USER_ATTR_QUERY_RS = int(DEF_GAME_VALET_PROPERTY + 52),
    //新增 ---增加加战斗力
    DEF_RPC_VALET_ADD_FIGHT_CAPACITY_RQ = int(DEF_GAME_VALET_PROPERTY + 53),//新增---增加加战斗力请求
    DEF_RPC_VALET_ADD_FIGHT_CAPACITY_RS = int(DEF_GAME_VALET_PROPERTY + 54),//

    //新增---减战斗力请求
    DEF_RPC_VALET_SUB_FIGHT_CAPACITY_RQ = int(DEF_GAME_VALET_PROPERTY + 55),//新增---减战斗力请求
    DEF_RPC_VALET_SUB_FIGHT_CAPACITY_RS = int(DEF_GAME_VALET_PROPERTY + 56),//

    //获取用户属性
    DEF_RPC_VALET_PROPERTY_INFO_RQ = int(DEF_GAME_VALET_PROPERTY + 57),//获取用户属性请求
    DEF_RPC_VALET_PROPERTY_INFO_RS = int(DEF_GAME_VALET_PROPERTY + 58),

    //获取用户属性(升级服务用)
    DEF_RPC_INTERNAL_VALET_PROPERTY_INFO_RQ = int(DEF_GAME_VALET_PROPERTY + 59),//获取用户属性请求
    DEF_RPC_INTERNAL_VALET_PROPERTY_INFO_RS = int(DEF_GAME_VALET_PROPERTY + 60),
    //--------------buff相关
    //加buff
    DEF_RPC_ADD_USER_BUFF_RQ = int(DEF_GAME_VALET_PROPERTY + 61),
    DEF_RPC_ADD_USER_BUFF_RS = int(DEF_GAME_VALET_PROPERTY + 62),
    //清除buff
    DEF_RPC_CLEAR_USER_BUFF_RQ = int(DEF_GAME_VALET_PROPERTY + 63),
    DEF_RPC_CLEAR_USER_BUFF_RS = int(DEF_GAME_VALET_PROPERTY + 64),
    //查询buff
    DEF_RPC_GET_USER_BUFF_RQ = int(DEF_GAME_VALET_PROPERTY + 65),
    DEF_RPC_GET_USER_BUFF_RS = int(DEF_GAME_VALET_PROPERTY + 66),

    //宝箱获取
    TREASURE_BOX_QUERY_RQ = int(DEF_GAME_VALET_PROPERTY + 67),
    TREASURE_BOX_QUERY_RS = int(DEF_GAME_VALET_PROPERTY + 68),

    //用户属性变化通知，equip/skill/car
    DEF_USER_ATTR_CHANGE_RQ = int(DEF_GAME_VALET_PROPERTY + 69),
    DEF_USER_ATTR_CHANGE_RS = int(DEF_GAME_VALET_PROPERTY + 70),

    //用户被囚禁消息msg处理
    DEF_USER_IMPRISON_MSG_RQ = int(DEF_GAME_VALET_PROPERTY + 71),

    DEF_RPC_ADD_USER_POTENTIAL_RQ = int(DEF_GAME_VALET_PROPERTY + 72),
    DEF_RPC_ADD_USER_POTENTIAL_RS = int(DEF_GAME_VALET_PROPERTY + 73),

    DEF_RPC_SUB_USER_POTENTIAL_RQ = int(DEF_GAME_VALET_PROPERTY + 74),
    DEF_RPC_SUB_USER_POTENTIAL_RS = int(DEF_GAME_VALET_PROPERTY + 75),

    DEF_RPC_GET_USER_POTENTIAL_RQ = int(DEF_GAME_VALET_PROPERTY + 76),
    DEF_RPC_GET_USER_POTENTIAL_RS = int(DEF_GAME_VALET_PROPERTY + 77),

    //体力恢复速度获取
    DEF_RPC_GET_USER_ENERGY_SPEED_RQ = int(DEF_GAME_VALET_PROPERTY + 78),
    DEF_RPC_GET_USER_ENERGY_SPEED_RS = int(DEF_GAME_VALET_PROPERTY + 79),

    // 批量查询用户声望接口
    DEF_RPC_GET_USER_PRESTIGE_RQ = int(DEF_GAME_VALET_PROPERTY + 82),
    DEF_RPC_GET_USER_PRESTIGE_RS = int(DEF_GAME_VALET_PROPERTY + 83),


    // 通知更新redis
    DEF_NOTIFY_UPATE_VALET_PROPERTY_REDIS_RQ = int(DEF_GAME_VALET_PROPERTY + 84),
    DEF_NOTIFY_UPATE_VALET_PROPERTY_REDIS_RS = int(DEF_GAME_VALET_PROPERTY + 85),

    DEF_VL_GOODS_PROFILE2_RQ = int(DEF_GAME_VALET_PROPERTY + 86),
    DEF_VL_GOODS_PROFILE2_RS = int(DEF_GAME_VALET_PROPERTY + 87),

    DEF_VALET_LOGIN_ATTR_PROFILE_RQ = int(DEF_RPC_VALET_SKILL_BASE + 88),
    DEF_VALET_LOGIN_ATTR_PROFILE_RS = int(DEF_RPC_VALET_SKILL_BASE + 89),
    DEF_VALET_ATTR_CACHE_CLEAR_RQ = int(DEF_RPC_VALET_SKILL_BASE + 90),

    //装备品质查询
    DEF_USER_EQUIP_QUALITY_QUERY_RQ = int(DEF_GAME_VALET_PROPERTY + 91),
    DEF_USER_EQUIP_QUALITY_QUERY_RS = int(DEF_GAME_VALET_PROPERTY + 92),

    DEF_GET_USER_BUFF_INTERNEL_RQ = int(DEF_GAME_VALET_PROPERTY + 93),
    DEF_GET_USER_BUFF_INTERNEL_RS = int(DEF_GAME_VALET_PROPERTY + 94),
    //加成来自buff和装备各自的值
    DEF_GET_USER_ADDITION_DISTINGUISH_VALUE_RQ = int(DEF_GAME_VALET_PROPERTY + 95),
    DEF_GET_USER_ADDITION_DISTINGUISH_VALUE_RS = int(DEF_GAME_VALET_PROPERTY + 96),

    DEF_VALET_SUB_EXP_RQ = int(DEF_GAME_VALET_PROPERTY + 97),
    DEF_VALET_SUB_EXP_RS = int(DEF_GAME_VALET_PROPERTY + 98),

    DEF_RPC_SUB_USER_POTENTIAL_EX_RQ = int(DEF_GAME_VALET_PROPERTY + 99),
    DEF_RPC_SUB_USER_POTENTIAL_EX_RS = int(DEF_GAME_VALET_PROPERTY + 100),
    
    //------------------
    //查询二度好友
    DEF_USER_DEG2_RQ = int(DEF_USER_DEGREE_FRIEND_BASE + 1), // 查询二度好友列表请求
    DEF_USER_DEG2_RS = int(DEF_USER_DEGREE_FRIEND_BASE + 2), // 查询二度好友列表返回

    DEF_RPC_GET_COMM_FRIEND_LIST_RQ = int(DEF_USER_DEGREE_FRIEND_BASE + 3), // 获取共同用户好友列表请求
    DEF_RPC_GET_COMM_FRIEND_LIST_RS = int(DEF_USER_DEGREE_FRIEND_BASE + 4), // 获取共同用户好友列表应答

    // 用户战斗力排名协议id
    DEF_USERCERANK_SVR_MSG_USERCERANK_RQ = int(DEF_RPC_FRIENDSRANK_BASE + 1),
    DEF_USERCERANK_SVR_MSG_USERCERANK_RS = int(DEF_RPC_FRIENDSRANK_BASE + 2),
    DEF_USERCERANK_SVR_MSG_USERCERANK_CHG_NOTIFY = int(DEF_RPC_FRIENDSRANK_BASE + 3),
    DEF_USERCERANK_SVR_MSG_REBUILD_USER_CE_RQ = int(DEF_RPC_FRIENDSRANK_BASE + 4),
    DEF_USERCERANK_SVR_MSG_REBUILD_USER_CE_RS = int(DEF_RPC_FRIENDSRANK_BASE + 5),
    DEF_USERCERANK_SVR_MSG_USERFRIENDRANKLIST_RQ = int(DEF_RPC_FRIENDSRANK_BASE + 6),
    DEF_USERCERANK_SVR_MSG_USERFRIENDRANKLIST_RS = int(DEF_RPC_FRIENDSRANK_BASE + 7),
    DEF_USERCERANK_SVR_MSG_USERSPECFRIENDSRANKINFO_RQ = int(DEF_RPC_FRIENDSRANK_BASE + 8),
    DEF_USERCERANK_SVR_MSG_USERSPECFRIENDSRANKINFO_RS = int(DEF_RPC_FRIENDSRANK_BASE + 9),



    DEF_RPC_USER_COMBAT_STATISTIC_RQ = int(DEF_COMBAT_BASE + 0),
    DEF_RPC_USER_COMBAT_STATISTIC_RS = int(DEF_COMBAT_BASE + 1),

    DEF_RPC_USER_START_COMBAT_RQ = int(DEF_COMBAT_BASE + 2),
    DEF_RPC_USER_START_COMBAT_RS = int(DEF_COMBAT_BASE + 3),

    DEF_RPC_GET_USER_BATTLE_FIELD_ID_RQ = int(DEF_COMBAT_BASE + 4),
    DEF_RPC_GET_USER_BATTLE_FIELD_ID_RS = int(DEF_COMBAT_BASE + 5),

    DEF_RPC_SET_USER_BATTLE_FIELD_ID_RQ = int(DEF_COMBAT_BASE + 6),
    DEF_RPC_SET_USER_BATTLE_FIELD_ID_RS = int(DEF_COMBAT_BASE + 7),

    DEF_RPC_USER_INCR_COMBAT_EXP_RQ = int(DEF_COMBAT_BASE + 8),
    DEF_RPC_USER_INCR_COMBAT_EXP_RS = int(DEF_COMBAT_BASE + 9),

    DEF_RPC_USER_UPGRADE_COMBAT_LV_RQ = int(DEF_COMBAT_BASE + 10),
    DEF_RPC_USER_UPGRADE_COMBAT_LV_RS = int(DEF_COMBAT_BASE + 11),

    DEF_RPC_USER_COMBAT_EXP_INFO_RQ = int(DEF_COMBAT_BASE + 12),
    DEF_RPC_USER_COMBAT_EXP_INFO_RS = int(DEF_COMBAT_BASE + 13),

    DEF_RPC_CLEAR_USER_BATTLE_FIELD_ID_RQ = int(DEF_COMBAT_BASE + 14),
    DEF_RPC_CLEAR_USER_BATTLE_FIELD_ID_RS = int(DEF_COMBAT_BASE + 15),

    DEF_RPC_USER_ASSIGN_COMPLETE_RQ = int(DEF_COMBAT_BASE + 16),
    DEF_RPC_USER_ASSIGN_COMPLETE_RS = int(DEF_COMBAT_BASE + 17),

    DEF_RPC_USER_CLEAR_COMBAT_INFO_CACHE_ID = int(DEF_COMBAT_BASE + 18),

    DEF_RPC_USER_COMBAT_RELATION_RQ = int(DEF_COMBAT_BASE + 19),
    DEF_RPC_USER_COMBAT_RELATION_RS = int(DEF_COMBAT_BASE + 20),

    DEF_RPC_USER_DISSOLUTION_BY_COMBAT_RQ = int(DEF_COMBAT_BASE + 21),
    DEF_RPC_USER_DISSOLUTION_BY_COMBAT_RS = int(DEF_COMBAT_BASE + 22),

    DEF_RPC_USER_COMBAT_UNIT_INFO_RQ = int(DEF_COMBAT_BASE + 23),
    DEF_RPC_USER_COMBAT_UNIT_INFO_RS = int(DEF_COMBAT_BASE + 24),

    // user vip level
    DEF_RPC_SET_USER_VIP_LEVEL_RQ = int(DEF_RPC_USER_VIP_LEVEL_BASE + 1), // 设置用户VIP等级请求
    DEF_RPC_SET_USER_VIP_LEVEL_RS = int(DEF_RPC_USER_VIP_LEVEL_BASE + 2), // 设置用户VIP等级应答


    DEF_RPC_DEL_USER_VIP_LEVEL_RQ = int(DEF_RPC_USER_VIP_LEVEL_BASE + 3), // 删除用户VIP等级请求
    DEF_RPC_DEL_USER_VIP_LEVEL_RS = int(DEF_RPC_USER_VIP_LEVEL_BASE + 4), // 删除用户VIP等级请求

    DEF_RPC_GET_USER_VIP_LEVEL_RQ = int(DEF_RPC_USER_VIP_LEVEL_BASE + 5), // 查询用户vip等级请求
    DEF_RPC_GET_USER_VIP_LEVEL_RS = int(DEF_RPC_USER_VIP_LEVEL_BASE + 6), // 查询用户vip等级应答


    DEF_RPC_GET_USER_LIST_VIP_LEVEL_RQ = int(DEF_RPC_USER_VIP_LEVEL_BASE + 7), // 批量查询用户VIP等级请求
    DEF_RPC_GET_USER_LIST_VIP_LEVEL_RS = int(DEF_RPC_USER_VIP_LEVEL_BASE + 8), // 批量查询用户VIP等级应答

    //废弃 不使用
    DEF_RPC_HOUSE_KEEPER_START_WORK_RQ_v0 = int(DEF_RPC_USER_VIP_LEVEL_BASE + 9), // 指派管家开始工作请求
    DEF_RPC_HOUSE_KEEPER_START_WORK_RS_v0 = int(DEF_RPC_USER_VIP_LEVEL_BASE + 10), // 指派管家开始工作应答
    //
    DEF_RPC_FREE_TAKE_CARD_QUERY_RQ    = int(DEF_RPC_USER_VIP_LEVEL_BASE + 11), // 查询免费抽卡次数请求
    DEF_RPC_FREE_TAKE_CARD_QUERY_RS    = int(DEF_RPC_USER_VIP_LEVEL_BASE + 12), // 查询免费抽卡次数应答

    DEF_RPC_USE_FREE_TAKE_CARD_RQ    = int(DEF_RPC_USER_VIP_LEVEL_BASE + 13), // 使用免费抽卡请求
    DEF_RPC_USE_FREE_TAKE_CARD_RS    = int(DEF_RPC_USER_VIP_LEVEL_BASE + 14), // 使用免费抽卡应答
    //废弃 不使用
    DEF_RPC_HOUSE_KEEPER_BUY_RQ_v0   = int(DEF_RPC_USER_VIP_LEVEL_BASE + 15), // 购买或者升级管家请求
    DEF_RPC_HOUSE_KEEPER_BUY_RS_v0   = int(DEF_RPC_USER_VIP_LEVEL_BASE + 16), // 购买或者升级管家应答
    //
    DEF_RPC_CLIENT_GET_USER_VIP_LEVEL_RQ = int(DEF_RPC_USER_VIP_LEVEL_BASE + 17), // 客户端查询用户vip等级请求
    DEF_RPC_CLIENT_GET_USER_VIP_LEVEL_RS = int(DEF_RPC_USER_VIP_LEVEL_BASE + 18), // 客户端查询用户vip等级应答

    // 管家相关协议ID
    DEF_RPC_HOUSE_KEEPER_STATUS_QUERY_RQ = int(DEF_RPC_HOUSE_KEEPER_BASE + 1), // 查询管家工作状态请求
    DEF_RPC_HOUSE_KEEPER_STATUS_QUERY_RS = int(DEF_RPC_HOUSE_KEEPER_BASE + 2), // 查询管家工作状态应答

    DEF_RPC_HOUSE_KEEPER_BUY_RQ          = int(DEF_RPC_HOUSE_KEEPER_BASE + 3), // 购买或者升级管家请求
    DEF_RPC_HOUSE_KEEPER_BUY_RS          = int(DEF_RPC_HOUSE_KEEPER_BASE + 4), // 购买或者升级管家应答

    DEF_RPC_HOUSE_KEEPER_PRICE_QUERY_RQ  = int(DEF_RPC_HOUSE_KEEPER_BASE + 5), // 查询管家购买花费请求
    DEF_RPC_HOUSE_KEEPER_PRICE_QUERY_RS  = int(DEF_RPC_HOUSE_KEEPER_BASE + 6), // 查询管家购买花费应答

    DEF_RPC_HOUSE_KEEPER_START_WORK_RQ   = int(DEF_RPC_HOUSE_KEEPER_BASE + 7), // 指派管家开始工作请求
    DEF_RPC_HOUSE_KEEPER_START_WORK_RS   = int(DEF_RPC_HOUSE_KEEPER_BASE + 8), // 指派管家开始工作应答

    DEF_RPC_HOUSE_KEEPER_OPEN_BOX_MSG_RQ = int(DEF_RPC_HOUSE_KEEPER_BASE + 9), // 管家开箱子发通知包
    DEF_RPC_HOUSE_KEEPER_OPEN_BOX_MSG_RS = int(DEF_RPC_HOUSE_KEEPER_BASE + 10), // 管家开箱子发通知包

    DEF_RPC_QUERY_HOUSE_KEEPER_WORK_STATUS_RQ = int(DEF_RPC_HOUSE_KEEPER_BASE + 11), //查询管家工作状态请求
    DEF_RPC_QUERY_HOUSE_KEEPER_WORK_STATUS_RS = int(DEF_RPC_HOUSE_KEEPER_BASE + 12), //查询管家工作状态应答

	DEF_GAME_DIAMOND_OPEN_BOX_RQ     = int(DEF_RPC_HOUSE_KEEPER_BASE + 13),            //h5活动立即开宝箱
	DEF_GAME_DIAMOND_OPEN_BOX_RS     = int(DEF_RPC_HOUSE_KEEPER_BASE + 14),



    DEF_RPC_HOUSE_KEEPER_MAX = int(DEF_RPC_HOUSE_KEEPER_BASE + 100), // max_id
    //

    //NPC协议Id
    DEF_NPC_SVR_MSG_CLIENT_OPEN_RQ = int(DEF_RPC_NPC_BASE + 1),     //客户端翻牌请求
    DEF_NPC_SVR_MSG_CLIENT_OPEN_RS = int(DEF_RPC_NPC_BASE + 2),
    DEF_NPC_SVR_MSG_NPCINFO_RQ = int(DEF_RPC_NPC_BASE + 3),     //查询npc用户信息
    DEF_NPC_SVR_MSG_NPCINFO_RS = int(DEF_RPC_NPC_BASE + 4),
    DEF_NPC_SVR_MSG_INSTANCE_SPE_QUALITY_RQ = int(DEF_RPC_NPC_BASE + 5),     //实例化指定品质npc
    DEF_NPC_SVR_MSG_INSTANCE_SPE_QUALITY_RS = int(DEF_RPC_NPC_BASE + 6),
    DEF_NPC_SVR_MSG_INSTANCE_SPE_ROLE_RQ = int(DEF_RPC_NPC_BASE + 7),     //实例化指定role npc
    DEF_NPC_SVR_MSG_INSTANCE_SPE_ROLE_RS = int(DEF_RPC_NPC_BASE + 8),
    //DEF_NPC_SVR_MSG_OPEN_TREASURE_BOX_RQ = int(DEF_RPC_NPC_BASE + 9),     //开宝箱
    //DEF_NPC_SVR_MSG_OPEN_TREASURE_BOX_RS = int(DEF_RPC_NPC_BASE + 10),
    DEF_NPC_SVR_MSG_NOTIFY_AREEST_RQ = int(DEF_RPC_NPC_BASE + 11),// 通知抓捕NPC
    DEF_NPC_SVR_MSG_NOTIFY_AREEST_RS = int(DEF_RPC_NPC_BASE + 12),// 通知抓补NPC应答
    DEF_NPC_SVR_CHECK_NEW_NPC_RQ = int(DEF_RPC_NPC_BASE + 13),// 检查用户是否有新npc可刷出
    DEF_NPC_SVR_CHECK_NEW_NPC_RS = int(DEF_RPC_NPC_BASE + 14),// 检查用户是否有新npc可刷出应答
    DEF_NPC_SVR_UPDATE_NPC_ADVANCE_RQ = int(DEF_RPC_NPC_BASE + 15),// 更新npc级别
    DEF_NPC_SVR_UPDATE_NPC_ADVANCE_RS = int(DEF_RPC_NPC_BASE + 16),// 更新npc级别应答


    DEF_VALET_SKILL_INFO_RQ = int(DEF_RPC_VALET_SKILL_BASE + 1),    //读取跟班技能等级信息请求
    DEF_VALET_SKILL_INFO_RS = int(DEF_RPC_VALET_SKILL_BASE + 2),    //读取跟班技能等级信息应答

    DEF_VALET_SKILL_UPGRADE_RQ = int(DEF_RPC_VALET_SKILL_BASE + 3),    //读取跟班技能升级请求
    DEF_VALET_SKILL_UPGRADE_RS = int(DEF_RPC_VALET_SKILL_BASE + 4),    //读取跟班技能升级应答

    DEF_VALET_SKILL_QUERY_RQ = int(DEF_RPC_VALET_SKILL_BASE + 5),    //查询下一技能等级属性请求
    DEF_VALET_SKILL_QUERY_RS = int(DEF_RPC_VALET_SKILL_BASE + 6),    //查询下一技能等级属性应答

    DEF_VALET_SKILL_ADDITION_RQ = int(DEF_RPC_VALET_SKILL_BASE + 7),    //跟班技能加成请求
    DEF_VALET_SKILL_ADDITION_RS = int(DEF_RPC_VALET_SKILL_BASE + 8),    //跟班技能加成应答

    DEF_VALET_SKILL_CLEAR_RQ = int(DEF_RPC_VALET_SKILL_BASE + 9),    //清除技能
    DEF_VALET_SKILL_CLEAR_RS = int(DEF_RPC_VALET_SKILL_BASE + 10),    //清除技能应答

    DEF_NPC_DIAMOND_BOX_RQ = int(DEF_RPC_VALET_SKILL_BASE + 11),    //钻石开宝箱
    DEF_NPC_DIAMOND_BOX_RS = int(DEF_RPC_VALET_SKILL_BASE + 12),    //钻石开宝箱应答

    DEF_VALET_SKILL_ATTR_INFO_RQ = int(DEF_RPC_VALET_SKILL_BASE + 13),    //读取跟班技能等级信息请求 服务器间使用
    DEF_VALET_SKILL_ATTR_INFO_RS = int(DEF_RPC_VALET_SKILL_BASE + 14),    //读取跟班技能等级信息应答 服务器间使用

    DEF_GET_NPC_FIGHT_DROPS_RQ  = int(DEF_RPC_VALET_SKILL_BASE + 15),   // 获取npc战斗的掉落请求
    DEF_GET_NPC_FIGHT_DROPS_RS  = int(DEF_RPC_VALET_SKILL_BASE + 16),   // 获取npc战斗的掉落应答

    DEF_VALET_SKILL_UPGRADE_ITEMS_RQ    = int(DEF_RPC_VALET_SKILL_BASE + 17),   // 技能升级所需物品列表请求
    DEF_VALET_SKILL_UPGRADE_ITEMS_RS    = int(DEF_RPC_VALET_SKILL_BASE + 18),   // 技能升级所需物品列表应答

    DEF_VALET_SKILL_LEVEL_INFO_RQ = int(DEF_RPC_VALET_SKILL_BASE + 19),    //获取技能等级请求
    DEF_VALET_SKILL_LEVEL_INFO_RS = int(DEF_RPC_VALET_SKILL_BASE + 20),    //获取技能等级应答


    DEF_NPC_SVR_MSG_OPEN_TREASURE_BOX_RQ = (DEF_RPC_NPC_LUCKY_CARD_BASE + 1),
    DEF_NPC_SVR_MSG_OPEN_TREASURE_BOX_RS = (DEF_RPC_NPC_LUCKY_CARD_BASE + 2),

    DEF_NPC_SVR_MSG_OPEN_TREASURE_BOX_INFO_RQ = (DEF_RPC_NPC_LUCKY_CARD_BASE + 3),
    DEF_NPC_SVR_MSG_OPEN_TREASURE_BOX_INFO_RS = (DEF_RPC_NPC_LUCKY_CARD_BASE + 4),

    DEF_USER_LUCKY_CARD_ROULETTE_RQ = (DEF_RPC_NPC_LUCKY_CARD_BASE + 5),
    DEF_USER_LUCKY_CARD_ROULETTE_RS = (DEF_RPC_NPC_LUCKY_CARD_BASE + 6),

    DEF_USER_LUCKY_CARD_ROULETTE_SHOW_RQ = (DEF_RPC_NPC_LUCKY_CARD_BASE + 7),
    DEF_USER_LUCKY_CARD_ROULETTE_SHOW_RS = (DEF_RPC_NPC_LUCKY_CARD_BASE + 8),
	
	DEF_USER_WEB_GET_LUCKY_CARD_RQ = (DEF_RPC_NPC_LUCKY_CARD_BASE+9),
	DEF_USER_WEB_GET_LUCKY_CARD_RS = (DEF_RPC_NPC_LUCKY_CARD_BASE+10),

    // 消息队列协议id
    DEF_PPMESSQUE_RQ = int(DEF_RPC_PPMESSQUE_BASE + 1),    //读取消息请求
    DEF_PPMESSQUE_RS = int(DEF_RPC_PPMESSQUE_BASE + 2),    //读取消息应答

    DEF_PPMESSQUE_RESET_READER_STATUS_RQ = int(DEF_RPC_PPMESSQUE_BASE + 3),    //重置reader状态请求
    DEF_PPMESSQUE_RESET_READER_STATUS_RS = int(DEF_RPC_PPMESSQUE_BASE + 4),    //重置reader状态应答

    DEF_PPMESSQUE_BATCH_RQ = int(DEF_RPC_PPMESSQUE_BASE + 5),    //读取消息请求，多条
    DEF_PPMESSQUE_BATCH_RS = int(DEF_RPC_PPMESSQUE_BASE + 6),    //读取消息应答，多条

    //背包操作
    DEF_GET_BAG_INFO_RQ = int(DEF_RPC_BAG_ITEM_BASE + 1),//获得背包信息
    DEF_GET_BAG_INFO_RS = int(DEF_RPC_BAG_ITEM_BASE + 2),

    DEF_BAG_USE_NPC_RQ = int(DEF_RPC_BAG_ITEM_BASE + 3),//使用npc
    DEF_BAG_USE_NPC_RS = int(DEF_RPC_BAG_ITEM_BASE + 4),


    DEF_BAG_USE_ITEM_RQ = int(DEF_RPC_BAG_ITEM_BASE + 5), //体力，杂志等非特殊道具
    DEF_BAG_USE_ITEM_RS = int(DEF_RPC_BAG_ITEM_BASE + 6),

    DEF_SVR_BAG_ADD_ITEM_RQ = int(DEF_RPC_BAG_ITEM_BASE + 7), //获得道具
    DEF_SVR_BAG_ADD_ITEM_RS = int(DEF_RPC_BAG_ITEM_BASE + 8),

    DEF_SVR_BAG_INFO_RQ = int(DEF_RPC_BAG_ITEM_BASE + 9), //服务器获得背包信息
    DEF_SVR_BAG_INFO_RS = int(DEF_RPC_BAG_ITEM_BASE + 10),

    DEF_SVR_SAVE_BAG_ITEM_RQ = int(DEF_RPC_BAG_ITEM_BASE + 11), //服务器保存背包
    DEF_SVR_SAVE_BAG_ITEM_RS = int(DEF_RPC_BAG_ITEM_BASE + 12),

    DEF_SVR_INIT_BAG_ITEM_RQ = int(DEF_RPC_BAG_ITEM_BASE + 13), //登陆初始化背包
    DEF_SVR_INIT_BAG_ITEM_RS = int(DEF_RPC_BAG_ITEM_BASE + 14),

    DEF_SVR_EQUIP_ADDITION_RQ = int(DEF_RPC_BAG_ITEM_BASE + 15), //装备加成
    DEF_SVR_EQUIP_ADDITION_RS = int(DEF_RPC_BAG_ITEM_BASE + 16),

    DEF_SVR_BAG_ITEM_INSTANCE_RQ = int(DEF_RPC_BAG_ITEM_BASE + 17), //道具实例化请求
    DEF_SVR_BAG_ITEM_INSTANCE_RS = int(DEF_RPC_BAG_ITEM_BASE + 18),

    DEF_SVR_BAG_FULL_CHECK_RQ = int(DEF_RPC_BAG_ITEM_BASE + 19),
    DEF_SVR_BAG_FULL_CHECK_RS = int(DEF_RPC_BAG_ITEM_BASE + 20),

    DEF_USER_EQUIP_PREVIEW_RQ = int(DEF_RPC_BAG_ITEM_BASE + 21),
    DEF_USER_EQUIP_PREVIEW_RS = int(DEF_RPC_BAG_ITEM_BASE + 22),

    DEF_SVR_EQUIP_PREVIEW_RQ = int(DEF_RPC_BAG_ITEM_BASE + 23),
    DEF_SVR_EQUIP_PREVIEW_RS = int(DEF_RPC_BAG_ITEM_BASE + 24),

    DEF_SVR_EQUIP_UPLIMIT_RQ = int(DEF_RPC_BAG_ITEM_BASE + 25),
    DEF_SVR_EQUIP_UPLIMIT_RS = int(DEF_RPC_BAG_ITEM_BASE + 26),

    DEF_SVR_BAG_GET_ITEM_RQ = int(DEF_RPC_BAG_ITEM_BASE + 27),
    DEF_SVR_BAG_GET_ITEM_RS = int(DEF_RPC_BAG_ITEM_BASE + 28),

    DEF_SVR_BAG_CONSUME_RQ = int(DEF_RPC_BAG_ITEM_BASE + 29),
    DEF_SVR_BAG_CONSUME_RS = int(DEF_RPC_BAG_ITEM_BASE + 30),

    DEF_SVR_BAG_CONSUME_MULTI_ITEM_RQ = int(DEF_RPC_BAG_ITEM_BASE + 31),
    DEF_SVR_BAG_CONSUME_MULTI_ITEM_RS = int(DEF_RPC_BAG_ITEM_BASE + 32),

    DEF_SVR_BAG_ADD_MUST_SUCCESS_RQ = int(DEF_RPC_BAG_ITEM_BASE + 33),
    DEF_SVR_BAG_ADD_MUST_SUCCESS_RS = int(DEF_RPC_BAG_ITEM_BASE + 34),

    DEF_SVR_BAG_REMAIN_CELL_RQ = int(DEF_RPC_BAG_ITEM_BASE+37),
    DEF_SVR_BAG_REMAIN_CELL_RS = int(DEF_RPC_BAG_ITEM_BASE+38),

    DEF_LOOT_SYS_RED_PACKET_RQ = int(DEF_SYS_RED_PACKET_BASE + 1), // 抢系统红包
    DEF_LOOT_SYS_RED_PACKET_RS = int(DEF_SYS_RED_PACKET_BASE + 2),

	//-----粉丝团-----
	DEF_FANSGROUP_QUERY_PACK_PRODUCE_RQ = int(DEF_SYS_RED_PACKET_BASE + 3), //查询当前掉落列表
	DEF_FANSGROUP_QUERY_PACK_PRODUCE_RS = int(DEF_SYS_RED_PACKET_BASE + 4),

	DEF_FANSGROUP_QUERY_MONEY_NUM_RQ = int(DEF_SYS_RED_PACKET_BASE + 5), //查询当前人民币余额
	DEF_FANSGROUP_QUERY_MONEY_NUM_RS = int(DEF_SYS_RED_PACKET_BASE + 6),

	DEF_FANSGROUP_OPEN_PACK_RQ = int(DEF_SYS_RED_PACKET_BASE + 7), //查询箱子物品请求
	DEF_FANSGROUP_OPEN_PACK_RS = int(DEF_SYS_RED_PACKET_BASE + 8),

//这里定义重了  ， 先用着有时间 改
	DEF_FANSGROUP_RECEIVE_PACK_RQ = int(DEF_SYS_RED_PACKET_BASE + 9), //收取箱子请求
	DEF_FANSGROUP_RECEIVE_PACK_RS = int(DEF_SYS_RED_PACKET_BASE + 10),

    DEF_USER_TOUCH_EVENT_END_GUIDE_RQ = int(DEF_SYS_RED_PACKET_BASE + 3), // 新手引导立即开宝箱
	DEF_USER_TOUCH_EVENT_END_GUIDE_RS = int(DEF_SYS_RED_PACKET_BASE + 4),

	DEF_FANSGROUP_REGISTER_PAIPAI_RQ  = int(DEF_SYS_RED_PACKET_BASE + 11),//粉丝团用户注册
	DEF_FANSGROUP_REGISTER_PAIPAI_RS  = int(DEF_SYS_RED_PACKET_BASE + 12),
	//-----粉丝团-----
	
    DEF_GET_USER_PACKAGE_INFO_RQ = int(DEF_USER_PACKAGE_BASE + 1),  // 获取背包信息
    DEF_GET_USER_PACKAGE_INFO_RS = int(DEF_USER_PACKAGE_BASE + 2),
    DEF_SAVE_USER_PACKAGE_INFO_RQ = int(DEF_USER_PACKAGE_BASE + 3), // 保存背包信息
    DEF_SAVE_USER_PACKAGE_INFO_RS = int(DEF_USER_PACKAGE_BASE + 4),
    DEF_SAVE_USER_EQUIP_INFO_RQ = int(DEF_USER_PACKAGE_BASE + 5), // 保存装备信息
    DEF_SAVE_USER_EQUIP_INFO_RS = int(DEF_USER_PACKAGE_BASE + 6),
    DEF_GET_USER_EQUIP_INFO_RQ = int(DEF_USER_PACKAGE_BASE + 7),  //获取装备信息
    DEF_GET_USER_EQUIP_INFO_RS = int(DEF_USER_PACKAGE_BASE + 8),

    DEF_USER_BAG_ADD_ITEM_RQ = int(DEF_USER_PACKAGE_BASE + 9),  //DB添加道具
    DEF_USER_BAG_ADD_ITEM_RS = int(DEF_USER_PACKAGE_BASE + 10),

    DEF_USER_BAG_CONSUME_ITEM_RQ = int(DEF_USER_PACKAGE_BASE + 11),  //DB消耗道具
    DEF_USER_BAG_CONSUME_ITEM_RS = int(DEF_USER_PACKAGE_BASE + 12),

    DEF_USER_BAG_EQUIP_UP_RQ = int(DEF_USER_PACKAGE_BASE + 13),  //DB穿装备道具
    DEF_USER_BAG_EQUIP_UP_RS = int(DEF_USER_PACKAGE_BASE + 14),

    DEF_USER_BAG_EQUIP_DOWN_RQ = int(DEF_USER_PACKAGE_BASE + 15),  //DB卸下装备道具
    DEF_USER_BAG_EQUIP_DOWN_RS = int(DEF_USER_PACKAGE_BASE + 16),

    DEF_USER_BAG_ITEM_INSTANCE_RQ = int(DEF_USER_PACKAGE_BASE + 17),  //DB实例化装备道具
    DEF_USER_BAG_ITEM_INSTANCE_RS = int(DEF_USER_PACKAGE_BASE + 18),

    DEF_GET_USER_SELL_LAST_TIME_RQ = int(DEF_USER_PACKAGE_BASE + 19),  //装备出售时间信息
    DEF_GET_USER_SELL_LAST_TIME_RS = int(DEF_USER_PACKAGE_BASE + 20),

    //npc 图鉴协议
    DEF_SVR_NPC_LIBRARY_ADD_RQ = int(DEF_RPC_NPC_LIBRARY_BASE + 1),// 增图鉴
    DEF_SVR_NPC_LIBRARY_ADD_RS = int(DEF_RPC_NPC_LIBRARY_BASE + 2),
    DEF_SVR_NPC_LIBRARY_QUERY_RQ = int(DEF_RPC_NPC_LIBRARY_BASE + 3),// 查图鉴
    DEF_SVR_NPC_LIBRARY_QUERY_RS = int(DEF_RPC_NPC_LIBRARY_BASE + 4),
    DEF_SVR_NPC_LIBRARY_NOTIFY = int(DEF_RPC_NPC_LIBRARY_BASE + 5), // 变化通知
    DEF_SVR_NPC_LIBRARY_UPGRADE_RQ = int(DEF_RPC_NPC_LIBRARY_BASE + 6), // 图鉴升级请求
    DEF_SVR_NPC_LIBRARY_UPGRADE_RS = int(DEF_RPC_NPC_LIBRARY_BASE + 7), // 图鉴升级应答
    DEF_SVR_NPC_LIBRARY_CHECK_RQ = int(DEF_RPC_NPC_LIBRARY_BASE + 8), // 图鉴检查
    DEF_SVR_NPC_LIBRARY_CHECK_RS = int(DEF_RPC_NPC_LIBRARY_BASE + 9), // 图鉴检查应答
    DEF_SVR_NPC_LIBRARY_NEXTLEVEL_INFO_RQ = int(DEF_RPC_NPC_LIBRARY_BASE + 10), // 下一级图鉴信息请求
    DEF_SVR_NPC_LIBRARY_NEXTLEVEL_INFO_RS = int(DEF_RPC_NPC_LIBRARY_BASE + 11), // 下一级图鉴信息应答
    DEF_SVR_NPC_LIBRARYS_CHECK_RQ = int(DEF_RPC_NPC_LIBRARY_BASE + 12), // 图鉴检查 批量
    DEF_SVR_NPC_LIBRARYS_CHECK_RS = int(DEF_RPC_NPC_LIBRARY_BASE + 13), // 图鉴检查应答
    DEF_SVR_NPC_QUERY_NPC_DEBRIS_RQ = int(DEF_RPC_NPC_LIBRARY_BASE + 14), // 获取用户npc碎片信息
    DEF_SVR_NPC_QUERY_NPC_DEBRIS_RS = int(DEF_RPC_NPC_LIBRARY_BASE + 15), // 获取用户npc碎片信息应答
    DEF_SVR_NPC_QUERY_NPC_FIGHTATTR_RQ = int(DEF_RPC_NPC_LIBRARY_BASE + 16), // 获取用户npc战斗属性
    DEF_SVR_NPC_QUERY_NPC_FIGHTATTR_RS = int(DEF_RPC_NPC_LIBRARY_BASE + 17), // 获取用户npc战斗属性应答
    DEF_SVR_NPC_FORCE_COMOUSE_RQ = int(DEF_RPC_NPC_LIBRARY_BASE + 18), // npc强制合成请求
    DEF_SVR_NPC_FORCE_COMOUSE_RS = int(DEF_RPC_NPC_LIBRARY_BASE + 19), // npc强制合成应答
    DEF_SVR_NPC_FIGHT_SKILL_INFO_RQ = int(DEF_RPC_NPC_LIBRARY_BASE + 20), // npc战斗技能信息请求
    DEF_SVR_NPC_FIGHT_SKILL_INFO_RS = int(DEF_RPC_NPC_LIBRARY_BASE + 21), // npc战斗技能信息应答
    DEF_SVR_NPC_USER_SCROLL_INFO_RQ = int(DEF_RPC_NPC_LIBRARY_BASE + 22), // 用户图纸请求
    DEF_SVR_NPC_USER_SCROLL_INFO_RS = int(DEF_RPC_NPC_LIBRARY_BASE + 23), // 用户图纸应答
	DEF_SVR_NPC_GET_SUIT_NPC_RQ = int(DEF_RPC_NPC_LIBRARY_BASE + 24), // 获取最佳掉落星卡请求
    DEF_SVR_NPC_GET_SUIT_NPC_RS = int(DEF_RPC_NPC_LIBRARY_BASE + 25), // 获取最佳掉落星卡应答
	DEF_SVR_NPC_GET_EXCHANGE_NPC_RQ = int(DEF_RPC_NPC_LIBRARY_BASE + 26), // 获取兑换星卡碎片请求
    DEF_SVR_NPC_GET_EXCHANGE_NPC_RS = int(DEF_RPC_NPC_LIBRARY_BASE + 27), // 获取兑换星卡碎片应答
	DEF_SVR_NPC_EXCHANGE_NPC_RQ = int(DEF_RPC_NPC_LIBRARY_BASE + 28), // 兑换星卡碎片请求
    DEF_SVR_NPC_EXCHANGE_NPC_RS = int(DEF_RPC_NPC_LIBRARY_BASE + 29), // 兑换星卡碎片应答
	DEF_SVR_NPC_GET_SUIT_NPC_BY_ROLE_RQ = int(DEF_RPC_NPC_LIBRARY_BASE + 30), // 根据role_id获取最佳掉落星卡请求
    DEF_SVR_NPC_GET_SUIT_NPC_BY_ROLE_RS = int(DEF_RPC_NPC_LIBRARY_BASE + 31), // 根据role_id获取最佳掉落星卡应答
    //跟班游戏囚禁相关接口
    DEF_VFGETPRISON_RELEATION_RQ = int(DEF_RPC_PRISON__BASE + 1),  //战斗前获取囚禁关系数据请求
    DEF_VFGETPRISON_RELEATION_RS = int(DEF_RPC_PRISON__BASE + 2),  //战斗前获取囚禁关系数据返回
    DEF_VFPRISON_FIGHTFINISH_RQ = int(DEF_RPC_PRISON__BASE + 3),   //囚禁战斗结束后反馈请求
    DEF_VFPRISON_FIGHTFINISH_RS = int(DEF_RPC_PRISON__BASE + 4),   //囚禁战斗结束后反馈返回
    DEF_VFPRISON_GET_USER_INPRISON_RQ = int(DEF_RPC_PRISON__BASE + 5),   //获取被囚禁的列表反馈请求
    DEF_VFPRISON_GET_USER_INPRISON_RS = int(DEF_RPC_PRISON__BASE + 6),   //获取被囚禁的列表反馈返回

    DEF_VFPRISON_GET_PRISONER_LIST_RQ = int(DEF_RPC_PRISON__BASE + 7),   //获取囚犯列表反馈请求
    DEF_VFPRISON_GET_PRISONER_LIST_RS = int(DEF_RPC_PRISON__BASE + 8),   //获取囚犯列表反馈返回

    DEF_VFPRISON_GET_PRISON_RELATION_OF_TWO_RQ = int(DEF_RPC_PRISON__BASE + 9),   //获取用户间囚禁关系请求
    DEF_VFPRISON_GET_PRISON_RELATION_OF_TWO_RS = int(DEF_RPC_PRISON__BASE + 10),   //获取用户间囚禁关系返回

    DEF_VFPRISON_GET_USER_STATUS_RQ = int(DEF_RPC_PRISON__BASE + 11),   //获取用户是否有囚犯或者被囚禁请求
    DEF_VFPRISON_GET_USER_STATUS_RS = int(DEF_RPC_PRISON__BASE + 12),   //获取用户是否有囚犯或者被囚禁返回

    // 夺宝能力 防盗能力获取
    DEF_GET_SNATCH_GUARD_RQ = int(DEF_RPC_SNATCH_BASE + 1),
    DEF_GET_SNATCH_GUARD_RS = int(DEF_RPC_SNATCH_BASE + 2),

    // 夺宝能力 防盗能力加成
    DEF_ADD_SNATCH_GUARD_RQ = int(DEF_RPC_SNATCH_BASE + 3),
    DEF_ADD_SNATCH_GUARD_RS = int(DEF_RPC_SNATCH_BASE + 4),

    //系统发放奖励接口
    DEF_SYS_AWARD_RQ = int(DEF_RPC_SYS_AWARD_BASE + 1),
    DEF_SYS_AWARD_RS = int(DEF_RPC_SYS_AWARD_BASE + 2),


    //--仇敌服务
    DEF_ADD_USER_HATE_VALUE_RQ = int(DEF_RPC_VALET_HATE_BASE + 1),
    DEF_ADD_USER_HATE_VALUE_RS = int(DEF_RPC_VALET_HATE_BASE + 2),

    DEF_GET_USER_HATE_VALUE_RQ = int(DEF_RPC_VALET_HATE_BASE + 3),
    DEF_GET_USER_HATE_VALUE_RS = int(DEF_RPC_VALET_HATE_BASE + 4),

    DEF_GET_MUSER_HATE_VALUE_RQ = int(DEF_RPC_VALET_HATE_BASE + 5),    // 获取所有仇恨值请求
    DEF_GET_MUSER_HATE_VALUE_RS = int(DEF_RPC_VALET_HATE_BASE + 6),

    DEF_GET_BATCH_USER_HATE_VALUE_RQ = int(DEF_RPC_VALET_HATE_BASE + 7),// 批量获取仇恨请求
    DEF_GET_BATCH_USER_HATE_VALUE_RS = int(DEF_RPC_VALET_HATE_BASE + 8),// 批量获取仇恨请求

    //邻居推荐
    DEF_RECOMMEND_FAMILY_RQ = int(DEF_RPC_FAMILY_BASE + 1),
    DEF_RECOMMEND_FAMILY_RS = int(DEF_RPC_FAMILY_BASE + 2),

    //系统推荐
    DEF_RECOMMEND_SYSTEM_FRIEND_RQ = int(DEF_RPC_SYSTEM_RECOMMEND_BASE + 1),
    DEF_RECOMMEND_SYSTEM_FRIEND_RS = int(DEF_RPC_SYSTEM_RECOMMEND_BASE + 2),

    //用户在线时长查询
    DEF_SVR_QUERY_USER_ONLINE_TIME_RQ = int(DEF_RPC_QUERY_USER_ONLINE_BASE + 1),
    DEF_SVR_QUERY_USER_ONLINE_TIME_RS = int(DEF_RPC_QUERY_USER_ONLINE_BASE + 2),
    //查询多人
    DEF_SVR_QUERY_MULTI_USER_ONLINE_TIME_RQ = int(DEF_RPC_QUERY_USER_ONLINE_BASE + 3),
    DEF_SVR_QUERY_MULTI_USER_ONLINE_TIME_RS = int(DEF_RPC_QUERY_USER_ONLINE_BASE + 4),

    DEF_SVR_NEW_USER_JUDGE_RQ = int(DEF_RPC_QUERY_USER_ONLINE_BASE + 5),
    DEF_SVR_NEW_USER_JUDGE_RS = int(DEF_RPC_QUERY_USER_ONLINE_BASE + 6),

    //处理c服务和php服务交互接口
    DEF_SVR_USER_LOGIN_NOTIFY_ID = int(DEF_RPC_WEB_RPC_BASE + 1),

    // 增加潜能,(旧潜能变晶石)
    DEF_ADD_USER_LEVEL_CONSUME_RQ = int(DEF_RPC_LEVEL_CONSUME_BASE + 1),
    DEF_ADD_USER_LEVEL_CONSUME_RS = int(DEF_RPC_LEVEL_CONSUME_BASE + 2),

    // 扣潜能,(旧潜能变晶石)
    DEF_SUB_USER_LEVEL_CONSUME_RQ = int(DEF_RPC_LEVEL_CONSUME_BASE + 3),
    DEF_SUB_USER_LEVEL_CONSUME_RS = int(DEF_RPC_LEVEL_CONSUME_BASE + 4),

    // 获取潜能,(旧潜能变晶石)
    DEF_GET_USER_LEVEL_CONSUME_RQ = int(DEF_RPC_LEVEL_CONSUME_BASE + 5),
    DEF_GET_USER_LEVEL_CONSUME_RS = int(DEF_RPC_LEVEL_CONSUME_BASE + 6),

    //装备实例存储服务
    DEF_QUERY_EQUIP_INFO_RQ = int(DEF_RPC_EQUIP_DBCS_RPC_BASE + 1), //查询装备属性
    DEF_QUERY_EQUIP_INFO_RS = int(DEF_RPC_EQUIP_DBCS_RPC_BASE + 2),

    DEF_SAVE_EQUIP_INFO_RQ = int(DEF_RPC_EQUIP_DBCS_RPC_BASE + 3),  //存储装备属性
    DEF_SAVE_EQUIP_INFO_RS = int(DEF_RPC_EQUIP_DBCS_RPC_BASE + 4),

    //查询每天物品掉落情况
    DEF_QUERY_GOODS_DAILY_LIMIT_RQ = int(DEF_RPC_GOODS_DROP_MAX_LIMIT_RPC_BASE + 1),  //查询用户每天单个物品掉落上限
    DEF_QUERY_GOODS_DAILY_LIMIT_RS = int(DEF_RPC_GOODS_DROP_MAX_LIMIT_RPC_BASE + 2),

    DEF_GET_USER_DAILY_DROP_GOODS_LIMIT_RQ = int(DEF_RPC_GOODS_DROP_MAX_LIMIT_RPC_BASE + 3), //批量查询用户每天掉落上限
    DEF_GET_USER_DAILY_DROP_GOODS_LIMIT_RS = int(DEF_RPC_GOODS_DROP_MAX_LIMIT_RPC_BASE + 4),

    DEF_GET_USER_ID_SCOPE_RQ = int(DEF_RPC_USER_ID_VERIFY_RPC_BASE + 1),
    DEF_GET_USER_ID_SCOPE_RS = int(DEF_RPC_USER_ID_VERIFY_RPC_BASE + 2),

    DEF_GET_USER_NEW_CARDINFO_LIST_RQ = int(DEF_RPC_USER_NEW_CARD_RPC_BASE + 1),    // 获取用户所有的新类型车列表
    DEF_GET_USER_NEW_CARDINFO_LIST_RS = int(DEF_RPC_USER_NEW_CARD_RPC_BASE + 2),

    DEF_GET_USER_CUR_CARDINFO_RQ = int(DEF_RPC_USER_NEW_CARD_RPC_BASE + 3), // 获取用户正使用的车
    DEF_GET_USER_CUR_CARDINFO_RS = int(DEF_RPC_USER_NEW_CARD_RPC_BASE + 4),

    // 车辆
    DEF_CAR_MANAGRE_ADD_CAR_RQ = int(DEF_RPC_CAR_MANAGER_BASE + 1),
    DEF_CAR_MANAGRE_ADD_CAR_RS = int(DEF_RPC_CAR_MANAGER_BASE + 2),
    DEF_CAR_MANAGRE_QUERY_USER_NEED_CAR_FUEL_RQ = int(DEF_RPC_CAR_MANAGER_BASE + 3),
    DEF_CAR_MANAGRE_QUERY_USER_NEED_CAR_FUEL_RS = int(DEF_RPC_CAR_MANAGER_BASE + 4),
    
    //------------------------ DEF_RPC_IMPRISON_OPERATE_BASE Begin ------------------------------------------------------------- 
    // ImprisonRpc.proto 定义
    DEF_IRPC_GET_MY_PRISON_EXTEND_LIST_RQ = int(DEF_RPC_IMPRISON_OPERATE_BASE + 1), //获取我的囚犯扩展列表，GetMyPrisonExtendList
    DEF_IRPC_GET_MY_PRISON_EXTEND_LIST_RS = int(DEF_RPC_IMPRISON_OPERATE_BASE + 2), //获取我的囚犯扩展列表应答 ExtendPrisonerList
    DEF_IRPC_GET_MY_PRISON_LIST_RQ = int(DEF_RPC_IMPRISON_OPERATE_BASE + 3), //获取我的囚犯列表，GetMyPrisonList
    DEF_IRPC_GET_MY_PRISON_LIST_RS = int(DEF_RPC_IMPRISON_OPERATE_BASE + 4), //获取我的囚犯列表应答 PrisonerList
    DEF_IRPC_GET_MY_IMPRISON_INFO_RQ = int(DEF_RPC_IMPRISON_OPERATE_BASE + 5), //取我的被囚信息GetMyImprisonInfo
    DEF_IRPC_GET_MY_IMPRISON_INFO_RS = int(DEF_RPC_IMPRISON_OPERATE_BASE + 6), //被囚信息应答ImprisonInfo
    DEF_IRPC_IMPRISON_RQ = int(DEF_RPC_IMPRISON_OPERATE_BASE + 7), //囚禁请求，ImprisonRQ
    DEF_IRPC_IMPRISON_RS = int(DEF_RPC_IMPRISON_OPERATE_BASE + 8), //囚禁应答，ImprisonRS
    DEF_IRPC_RELEASE_PRISON_RQ = int(DEF_RPC_IMPRISON_OPERATE_BASE + 9), //释放请求，ReleasePrisonerRQ
    DEF_IRPC_RELEASE_PRISON_RS = int(DEF_RPC_IMPRISON_OPERATE_BASE + 10), //释放应答，ReleasePrisonerRS
    DEF_IRPC_SMART_CLEAN_PRISON_RQ = int(DEF_RPC_IMPRISON_OPERATE_BASE + 11), //释放请求，SmartCleanPrisonRQ
    DEF_IRPC_SMART_CLEAN_PRISON_RS = int(DEF_RPC_IMPRISON_OPERATE_BASE + 12), //释放应答，SmartCleanPrisonRS

    //------------------------ DEF_RPC_IMPRISON_OPERATE_BASE End -------------------------------------------------------------
    
    // 宝箱推荐
    DEF_PUSH_CHEST_EVENT_ID = int(DEF_RPC_CHEST_RECOMMEND_BASE + 1),      //推送宝箱事件

    DEF_SUBSCRIBE_CHEST_EVENT_RQ = int(DEF_RPC_CHEST_RECOMMEND_BASE + 2), //订阅宝箱事件请求
    DEF_SUBSCRIBE_CHEST_EVENT_RS = int(DEF_RPC_CHEST_RECOMMEND_BASE + 3), //订阅宝箱事件应答
    DEF_CHECK_IMPRISON_CHG_RQ = int(DEF_RPC_CHEST_RECOMMEND_BASE + 4),    //检查囚禁变化请求
    DEF_CHECK_IMPRISON_CHG_RS = int(DEF_RPC_CHEST_RECOMMEND_BASE + 5),    //检查囚禁变化应答
    DEF_PUSH_IMPRISON_EVENT_ID = int(DEF_RPC_CHEST_RECOMMEND_BASE + 6),   // 推送囚禁事件
    DEF_SYNC_IMPRISON_CHG_RQ = int(DEF_RPC_CHEST_RECOMMEND_BASE + 7),     // 同步囚禁变化请求
    DEF_SYNC_IMPRISON_CHG_RS = int(DEF_RPC_CHEST_RECOMMEND_BASE + 8),     // 同步囚禁变化应答
    DEF_DATA_SYNC_PUSH_TO_DISPATCH_SVR_RQ = int(DEF_RPC_CHEST_RECOMMEND_BASE + 9), //时间分发服务向事件推送服务请求同步数据 rq
    DEF_DATA_SYNC_PUSH_TO_DISPATCH_SVR_RS = int(DEF_RPC_CHEST_RECOMMEND_BASE + 10),//时间分发服务向事件推送服务请求同步数据 rs
    DEF_DUMP_IMPRISON_INFO_RQ = int(DEF_RPC_CHEST_RECOMMEND_BASE + 11),  // 请求dump囚禁信息 rq
    DEF_DUMP_IMPRISON_INFO_RS = int(DEF_RPC_CHEST_RECOMMEND_BASE + 12),  // 请求dump囚禁信息 rs
    DEF_SVR_LOGIN_RQ = int(DEF_RPC_CHEST_RECOMMEND_BASE + 13),           // 服务器之间的登录请求
    DEF_SVR_LOGIN_RS = int(DEF_RPC_CHEST_RECOMMEND_BASE + 14),           // 服务器之间的登录应答

    DEF_GET_VALET_RED_STATUS_RQ = int(DEF_RPC_CHEST_RECOMMEND_BASE + 15), // 获取跟班红包状态请求
    DEF_GET_VALET_RED_STATUS_RS = int(DEF_RPC_CHEST_RECOMMEND_BASE + 16), // 获取跟班红包状态应答
    DEF_BATCH_GET_VALET_RED_STATUS_RQ = int(DEF_RPC_CHEST_RECOMMEND_BASE + 17), // 批量获取跟班红包状态请求
    DEF_BATCH_GET_VALET_RED_STATUS_RS = int(DEF_RPC_CHEST_RECOMMEND_BASE + 18), // 批量获取跟班红包状态应答

	DEF_WEB_QUERY_RED_PACKET_STATUS_INFO_RQ = int(DEF_RPC_CHEST_RECOMMEND_BASE + 19),        //Web查询内存状态信息请求
	DEF_WEB_QUERY_RED_PACKET_STATUS_INFO_RS = int(DEF_RPC_CHEST_RECOMMEND_BASE + 20),        //Web查询内存状态信息应答
	DEF_WEB_CHECK_RELATION_RQ = int(DEF_RPC_CHEST_RECOMMEND_BASE + 21),                      //Web校验正反向好友订阅关系请求
	DEF_WEB_CHECK_RELATION_RS = int(DEF_RPC_CHEST_RECOMMEND_BASE + 22),                      //Web校验正反向好友订阅关系应答
	DEF_WEB_REBUILD_SUBSCRIBE_RELATION_RQ = int(DEF_RPC_CHEST_RECOMMEND_BASE + 23),          //Web强制重新构建订阅关系请求
	DEF_WEB_REBUILD_SUBSCRIBE_RELATION_RS = int(DEF_RPC_CHEST_RECOMMEND_BASE + 24),          //Web强制重新构建订阅关系应答
	DEF_WEB_FLUSH_RED_PACKET_STATUS_RQ = int(DEF_RPC_CHEST_RECOMMEND_BASE + 25),             //Web推送好友红包状态给用户请求
	DEF_WEB_FLUSH_RED_PACKET_STATUS_RS = int(DEF_RPC_CHEST_RECOMMEND_BASE + 26),             //Web推送好友红包状态给用户应答
	DEF_RED_STATUS_QUERY_REVERSE_RELATION_RQ = int(DEF_RPC_CHEST_RECOMMEND_BASE + 27),		// 从Dispatch获取用户反向关>系请求
	DEF_RED_STATUS_QUERY_REVERSE_RELATION_RS = int(DEF_RPC_CHEST_RECOMMEND_BASE + 28),		// 从Dispatch获取用户反向关>系应答

    // PHP H5等服务调用接口类型
    DEF_PHP_FRIENDS_HISTORY_RQ  = int(DEF_RPC_PHP_SERVER_BASE + 1),    // PHP调用， 点击邀请链接获取好友抓跟班列表请求
    DEF_PHP_FRIENDS_HISTORY_RS  = int(DEF_RPC_PHP_SERVER_BASE + 2),    // PHP调用， 点击邀请链接获取好友抓跟班列表应答

    DEF_EXCHANGE_MONEY_RQ = (DEF_RPC_PHP_SERVER_BASE + 3),//兑换钱币（目前是金币换成元宝）
    DEF_EXCHANGE_MONEY_RS = (DEF_RPC_PHP_SERVER_BASE + 4),//

    //自动经验金币加成
    DEF_SLOT_ADDITION_AUTO_PRODUCTION_RQ = (DEF_BUFF_ADDITION_BASE + 1),//
    DEF_SLOT_ADDITION_AUTO_PRODUCTION_RS = (DEF_BUFF_ADDITION_BASE + 2),//

    // 钻石购买buff（H5)
    DEF_BUY_BUFF_WITH_DIAMOND_RQ  = (DEF_BUFF_ADDITION_BASE + 3),
    DEF_BUY_BUFF_WITH_DIAMOND_RS  = (DEF_BUFF_ADDITION_BASE + 4),

    DEF_USER_GET_STEAL_BUFF_RQ = (DEF_BUFF_ADDITION_BASE + 5),//偷东西经验金币buff加成
    DEF_USER_GET_STEAL_BUFF_RS = (DEF_BUFF_ADDITION_BASE + 6),//

    DEF_USER_BUFF_REMAIN_TIMES_RQ = (DEF_BUFF_ADDITION_BASE + 7),//buff剩余时间查询
    DEF_USER_BUFF_REMAIN_TIMES_RS = (DEF_BUFF_ADDITION_BASE + 8),//

    DEF_USER_BUY_GOODS_RQ = (DEF_BUFF_ADDITION_BASE + 9),
    DEF_USER_BUY_GOODS_RS = (DEF_BUFF_ADDITION_BASE + 10),
    // -------------------------金币---------------------------
    DEF_USER_BATCH_ADD_GOLDCOIN_RQ = (DEF_RPC_GOLDCOIN_BASE + 1), // 批量加
    DEF_USER_BATCH_ADD_GOLDCOIN_RS = (DEF_RPC_GOLDCOIN_BASE + 2), // 批量加

    DEF_BATCH_ADD_BATCH_ADD_EXP_RQ = (DEF_VALET_USER_DATA_BASE + 1),
    DEF_BATCH_ADD_BATCH_ADD_EXP_RS = (DEF_VALET_USER_DATA_BASE + 2),

    DEF_NEW_USER_GUIDE_UPGRADE_RQ = (DEF_VALET_USER_DATA_BASE + 4),
    DEF_NEW_USER_GUIDE_UPGRADE_RS = (DEF_VALET_USER_DATA_BASE + 5),

    // ----------------------- 抢红包游戏 ---------------------
    DEF_REDPACK_PREPARE_SNATCH_RQ = int(DEF_REDPACK_GAME_BASE + 1),  // 准备抢红包
    DEF_REDPACK_PREPARE_SNATCH_RS = int(DEF_REDPACK_GAME_BASE + 2),

    DEF_REDPACK_NOTICE_EXPIRE_STATUS_RQ = int(DEF_REDPACK_GAME_BASE + 3), //通知过期红包
    DEF_REDPACK_NOTICE_EXPIRE_STATUS_RS = int(DEF_REDPACK_GAME_BASE + 4),
    
    DEF_RPC_REDPACK_GAME_MASTER_RANK_LIST_RQ = int(DEF_REDPACK_GAME_BASE + 5), //查询达人榜单排名列表请求
    DEF_RPC_REDPACK_GAME_MASTER_RANK_LIST_RS = int(DEF_REDPACK_GAME_BASE + 6),


    DEF_FANS_QUERY_USER_RMB_RQ = int(DEF_RPC_FANS_DATA_BASE + 1),    //查询rmb余额
    DEF_FANS_QUERY_USER_RMB_RS = int(DEF_RPC_FANS_DATA_BASE + 2),
	// ----------------------- 胶囊 ---------------------

    DEF_GET_CAPSULE_RQ = (DEF_RPC_CAPSULE_BASE + 1), // 查胶囊
    DEF_GET_CAPSULE_RS = (DEF_RPC_CAPSULE_BASE + 2), //

    DEF_ADD_CAPSULE_RQ = (DEF_RPC_CAPSULE_BASE + 3), // 加胶囊
    DEF_ADD_CAPSULE_RS = (DEF_RPC_CAPSULE_BASE + 4),

    DEF_SUB_CAPSULE_RQ = (DEF_RPC_CAPSULE_BASE + 5), // 扣胶囊
    DEF_SUB_CAPSULE_RS = (DEF_RPC_CAPSULE_BASE + 6),
	
	// ----------------------工坊--------------------------
	DEF_WORK_SHOP_VEHICLE_ADD_RQ    = int(DEF_RPC_WORK_SHOP_BASE + 0), // 添加车辆/配件
	DEF_WORK_SHOP_VEHICLE_ADD_RS    = int(DEF_RPC_WORK_SHOP_BASE + 1),
	DEF_WORK_SHOP_VEHICLE_USE_RQ    = int(DEF_RPC_WORK_SHOP_BASE + 2), // 使用车辆
	DEF_WORK_SHOP_VEHICLE_USE_RS    = int(DEF_RPC_WORK_SHOP_BASE + 3),
	DEF_WORK_SHOP_VEHICLE_UPDATE_RQ = int(DEF_RPC_WORK_SHOP_BASE + 4), // 更新车辆/配件
	DEF_WORK_SHOP_VEHICLE_UPDATE_RS = int(DEF_RPC_WORK_SHOP_BASE + 5),
	DEF_WORK_SHOP_VEHICLE_QUERY_RQ  = int(DEF_RPC_WORK_SHOP_BASE + 6), // 查询车辆/配件
	DEF_WORK_SHOP_VEHICLE_QUERY_RS  = int(DEF_RPC_WORK_SHOP_BASE + 7),

    DEF_DEFAULT_RPC_PACKET_TYPE_MAX = int(DEF_DEFAULT_RPC_PACKET_BASE + USHRT_MAX)
};

#endif
